### ISSUE TITLE
[Firefox] Challenges do not filter by subtracks

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#100]
Bug Title: Most of the times on filtering with subtracks, list keeps on loading infinitely.

Steps to Reproduce:
1. Open page with subtracks filtering - https://www.topcoder.com/challenges?filter[subtracks][0]=BUG_HUNT
(Not able to reproduce each time, so reload if it loads)

Expected Result:
Should load in reasonable time

Actual Result:
Does not load most of the times (remains in loading state infinitely). Also sometimes consumes lot of cpu during the process.

Screenshots or screencast:
![3](https://user-images.githubusercontent.com/32861951/76162979-59d75a00-6168-11ea-8b44-d1db8f1ca2d5.png)
CPU jumped from 20% to 40-60% and remains there. Also the page remains as is.

Device/OS/Browser Information:
Ubuntu 18.04 LTS, Firefox 73.0.1 (64-bit),Intel i5 7gen

**Comment by g1tman** [comment]
Tested on both ubuntu & windows

**Comment by winterflame** [comment]
Cannot reproduce - works fine now.
