### ISSUE TITLE
Search - The button is clickable even if no data is entered

### ISSUE THREAD

**Issue by martian360** [topcoder-platform/qa-fun#102]
**Steps to reproduce:**

1. Go to https://www.topcoder.com/challenges. 
2. Without typing anything in search bar hover over the search icon

**Expected results:**
Since nothing is entered in search bar the search button should not be clickable on hover

**Actual results:**
The button turns blue and cursor turns into hand symbol

**Screenshot**
![Search](https://user-images.githubusercontent.com/60810387/76163261-ac197a80-616a-11ea-9a0f-18a90b80eeaf.png)

**Device/OS:**
Laptop | Windows 10 (64bit)

**Browser Information:**
Google Chrome 80.0.3987.122

**Comment by winterflame** [comment]
Duplicated with #14
