### ISSUE TITLE
Image issue on Home screen

### ISSUE THREAD

**Issue by tchackerc** [topcoder-platform/qa-fun#109]
**Steps to Reproduce:**
**Open website**  https://www.topcoder.com/
**Expected Result:**
Expected result : Image should be displayed in proper alignment 
**Actual Result:**
Actual result : Image is not displayed correctly. 
**Screenshots or screencast:**

![1](https://user-images.githubusercontent.com/60475043/78253442-07dce680-7512-11ea-9c04-bf238e72969a.png)

**Device/OS/Browser Information:**
Detailed device:Desktop, Operating System: Windows7   and Browser information; Chrome

**Comment by winterflame** [comment]
Not a bug.

**Comment by tchackerc** [comment]
Please suggest,how it is not a bug?

**Comment by tchackerc** [comment]
Could you provide any doc to validate this design?

**Comment by winterflame** [comment]
@tchackerc There is no way to arrange three images properly as their sizes are different. No design document available.
