### ISSUE TITLE
Clicking Keywords count not included in the filter count

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/qa-fun#11]
![filter](https://user-images.githubusercontent.com/37167721/75688557-bc37e280-5cb0-11ea-8873-541463b39f53.jpg)

1. Go to: https://www.topcoder.com/challenges?bucket=reviewOpportunities&filter[tags][0]=3D%20Reconstruction&filter[tags][1]=Distributive%20Aggregation&filter[tags][2]=Actian%20Data%20Management&filter[tags][3]=Ab%20Initio
2. On the right side, click the Filter icon 
3.  Select the keywords inthe keyword section. Click the different keywords,
4. Observe the filter count

**Expected Result:** When you click the Keywords in the keyword section and input the keywords should show the exact number of keyword count

**Actual Result:** The filter count is not accurate after clicking the keywords in the Keyword section
[filter.zip](https://github.com/topcoder-platform/qa-fun/files/4276093/filter.zip)

Device/OS: Laptop | linux (32bit)

Browser Information: Firefox Version 73.0.1 (32-bit)

**Comment by winterflame** [comment]
Not a bug - the filters count is not the same as the keywords count.
