### ISSUE TITLE
 "REGISTER NOW" button is clickable even after user logged in to topcoder.com

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#112]
Steps to Reproduce:
1. Login to Tocoder.com
2. Go to Community page
3. Hover mouse to "REGISTER NOW" button
Observe

Expected Result:
 "REGISTER NOW" button should be disabled after login

Actual Result:
 "REGISTER NOW" button is clickable even after user logged in to topcoder.com

Screenshots or screencast:

[2.zip](https://github.com/topcoder-platform/qa-fun/files/4421286/2.zip)
![2](https://user-images.githubusercontent.com/51490878/78254023-ed573d00-7512-11ea-818e-979c22f80e1f.png)

Device/OS/Browser Information:
Windows 10 64 bit.
Chrome Version 80.0.3987.162 (Official Build) (64-bit)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/78254031-f1835a80-7512-11ea-968f-d01def3b727b.png)
![Uploading BrowserInfo_Chrome_80.0.3987.162.png…]()

**Comment by winterflame** [comment]
Not a UI issue.
