### ISSUE TITLE
[Functional bug] Filter feature does not work

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/qa-fun#114]
## Step To Reproduce
1. Go to tracks > QA
2. Click Show Filter
3. Change Start Date to Jan 3, 2019 and then click apply filter.

## Actual Result
Nothing Found

## Expected Result
Article that created between Jan 3,2019 to today (2020-04-02) will shown.

## Screenshot
- This article have to be shown after filtered because it created at march 2020)

![stepToReproduce](https://www.dropbox.com/s/q053ri9g73r8mm7/filter_fiture_before.png?raw=1)

- But the actual results is wrong. It shown no article after filtered.

![](https://www.dropbox.com/s/2t58zkz261z27lo/filter_feature_after.png?raw=1)

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 
c. Browser: Google Chrome
Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Valid functional bug but not UI bug.
