### ISSUE TITLE
No boxizing enabled in the container

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/qa-fun#116]
**Steps to Reproduce:**

1.Go to: https://www.topcoder.com/
2. Go to: https://www.topcoder.com/community/learn
[scroll.zip](https://github.com/topcoder-platform/qa-fun/files/4421339/scroll.zip)

3.Observe
**Expected Result:**
There should be no scroll icons on the page 
**Actual Result:**after loading
There are scroll icons at the bottom and no box-sing is enabled in the page container

****Environment:**Chrome:Version 80.0.3987.149
![scroll4](https://user-images.githubusercontent.com/37167721/78346413-b2531900-75a7-11ea-9337-2e7546937b5d.png)

**Comment by winterflame** [comment]
cannot reproduce

**Comment by Rokit12** [comment]
https://www.topcoder.com/community/learn     in Chrome browser

**Comment by winterflame** [comment]
@Rokit12  Many pages have this issue for you? You're using Linux system, can you change the dock position (it's currently on the left side and occupies some space of the Chrome browser) to the bottom of the screen?

**Comment by Rokit12** [comment]
Not all pages have this issue

**Comment by winterflame** [comment]
@Rokit12 OK, please attach a screenshot for this ticket. Thanks.

**Comment by Rokit12** [comment]
Thank you sir.check the attachment
