### ISSUE TITLE
My Profile 404 HTTP Error

### ISSUE THREAD

**Issue by shamya555** [topcoder-platform/qa-fun#119]
Bug Title: MY PROFILE 404 HTTP ERROR

Steps to Reproduce:

1. Go to https://www.topcoder.com/
2. Click dropdown arrow next to User ID
3. Click My Profile

Expected Result:

Profile details should be displayed

Actual Result:

404 HTTP Error 

Screenshots or screencast:
![image](https://user-images.githubusercontent.com/37837140/78254716-ef6dcb80-7513-11ea-9341-3dd643ee4e2e.png)

Device/OS/Browser Information:
HP Laptop
Windows 10
Chrome

**Comment by winterflame** [comment]
Functional bug, not UI bug.
