### ISSUE TITLE
The links in the [TECAMS] UI Prototype challenge not clickable

### ISSUE THREAD

**Issue by DracoHeart** [topcoder-platform/qa-fun#12]
Step to reproduce:
1. Go to URL https://www.topcoder.com/challenges
2. Click on the "Open for registration" at the right side bar
3. Scroll down and find the "[TECAMS] UI Prototype challenge" > click on the title
4. Scroll down the challenge detail page to "Application requirements" and "2. Landing page"
5. Click on the link in this section which have the underline texts
6. Observe

Expexted result:
When the user click on the link, the link should be clickable and working and redirects to a page

Actual result:
When the user click on the link, nothing happen. The link is not clickable.

Screenshots or screencast:

![Bug1](https://user-images.githubusercontent.com/52654773/75688917-42691e80-5cdb-11ea-8d68-c189e64390b8.png)

[Bug1.zip](https://github.com/topcoder-platform/qa-fun/files/4276112/Bug1.zip)

Device/OS/Browser Information:
Laptop/macOS Catalina 10.15.2/Firefox version 73.0.1 (64-bit)

**Comment by winterflame** [comment]
Not a bug. It is an image in the specification - https://www.topcoder.com/challenges/30117651
