### ISSUE TITLE
Random shape appearing on clicking community image

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#120]
Bug Title: <Random shape appearing on clicking community image
Steps to Reproduce:
1.Go to https://www.topcoder.com/
2. Click on Community Image
Expected Result:
No image should appear on clicking Community image
Actual Result:
Image is appearing on clicking community Image 
Device/OS/Browser Information:
Google Chrome Version 80.0.3987.162 (Official Build) (64-bit)
Screenshots or screencast:[Error 1.zip](https://github.com/topcoder-platform/qa-fun/files/4421346/Error.1.zip)

**Comment by winterflame** [comment]
![image](https://user-images.githubusercontent.com/4590317/78328083-db2bdc00-75b0-11ea-9229-ad84e3a111c7.jpg)
