### ISSUE TITLE
GITLAB - LINKED ACCOUNT

### ISSUE THREAD

**Issue by shamya555** [topcoder-platform/qa-fun#125]
Steps to Reproduce:

1. Go to https://www.topcoder.com/
2. Click dropdown arrow next to User ID
3. Click Settings
4. Go to Account
5. Under Account, click Linked Accounts
6. Click Github

Expected Result:

Linked Github account should be displayed

Actual Result:

A window opens and closes immediately

Screenshots or screencast:

![image](https://user-images.githubusercontent.com/37837140/78255402-e29da780-7514-11ea-95dc-a4ecee13dfc6.png)
![image](https://user-images.githubusercontent.com/37837140/78255656-3e683080-7515-11ea-8456-795f1ca8c6a7.png)

Device/OS/Browser Information:
HP Laptop
Windows 10
Chrome

**Comment by winterflame** [comment]
functional bug
