### ISSUE TITLE
Accepting invalid email id without throwing an error message

### ISSUE THREAD

**Issue by su832665** [topcoder-platform/qa-fun#127]
Steps to reproduce:

1. Enter the URL - https://www.topcoder.com/
2. Click on More Category >> Contact Us link
3. Enter invalid email id and enter other fields 
4. Click on submit

Expected Result: system should throw an error saying" Enter valid email id".

Actual Result : USer is able to submit the form
Device/OS/Browser Information - Chrome version Version 80.0

![image](https://user-images.githubusercontent.com/49670274/78255716-52ac2d80-7515-11ea-862d-a062847a7c1c.png)

**Comment by winterflame** [comment]
functional bug
