### ISSUE TITLE
[Functional bug] - **view all results** link didnot work

### ISSUE THREAD

**Issue by Citra-citoru** [topcoder-platform/qa-fun#128]
## Step To Reproduce
1. Go to tracks > QA
2. Click Show Filter
3. Type UI in search input and then click link **view all results**

## Actual Result
No change after link  **view all results** clicked.

## Expected Result
Article with only keyword **UI**, will shown in the UI.

## Screenshot
-Type UI at search menu and then click link **view all results**

![](https://www.dropbox.com/s/08altmzvdlhd8fj/search_before.png?raw=1)

- No changes happened when we click the link
![](https://www.dropbox.com/s/0mmlu6dad1tavbs/search_after.png?raw=1)

## Device/OS/Browser Information:
a. Device: Lenovo (laptop)
Processor : AMD A9-9420 RADEON R5, 5  Compute Cores 2C+3G 3.00 GHz
RAM : 8 GB
System Type: 64 Bit OS, x64-based processor
Pen or touch: no pen or touch
b. OS: Windows 10 
c. Browser: Google Chrome
Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Valid functional bug but not UI bug.
