### ISSUE TITLE
Case studies >>On Mouse hover in search button  animation not happening.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#130]
Bug Title: <Case studies >>On Mouse hover in search button  animation not happening.>
Steps to reproduce -

1. Hit the URL - https://www.topcoder.com/
2. Login as topcoder .
3. Click on More link >> Select Resources menu and click on the hyperlink.
4. Mouse hover top and down in the Search button , noted there is a animation on mousehover . (Screen1)
Now,
5. Goto Case studies link menu ,click on the hyperlink.
6. Mouse hover in the Search button (Screen 2)

Expected Result : Animation should happen entire application in search button.
Actual Result : On Mouse hover in search button  animation not happening.

Browser : Chrome version 80
Screen1
![image](https://user-images.githubusercontent.com/61318135/78256000-9ef76d80-7515-11ea-9824-47bd9db0bf32.png)

Screen2
![image](https://user-images.githubusercontent.com/61318135/78255914-87b88000-7515-11ea-8cb7-395fc7784330.png)

**Comment by winterflame** [comment]
It's a functional bug.
