### ISSUE TITLE
Background color of notification icon is not changing when hover mouse on it.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#131]
Steps to Reproduce:
1. Login to topcoder.com
2. Go to COMMUNITY page
3. hove mouse to notification icon
4. hover mouse to search icon
Observe difference

Expected Result:
Background color of notification icon should get changed when hover mouse on it.

Actual Result:
Background color of notification icon is not changing when hover mouse on it.

Screenshots or screencast:
[Uploading 4.zip…]()

Device/OS/Browser Information:
Windows 10 64 bit.
Chrome Version 80.0.3987.162 (Official Build) (64-bit)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/78256285-f4cc1580-7515-11ea-9a2a-96e3a0665cb3.png)
![BrowserInfo_Chrome_80 0 3987 162](https://user-images.githubusercontent.com/51490878/78256296-f7c70600-7515-11ea-8711-64ac4371cbdb.png)

**Comment by winterflame** [comment]
Screenshot not available.

**Comment by coderkid19** [comment]
@winterflame : video is attached

**Comment by coderkid19** [comment]
![4](https://user-images.githubusercontent.com/51490878/78325587-ac543c80-7595-11ea-9256-32bcf24492cc.png)
