### ISSUE TITLE
Phone number field limit is not enabled

### ISSUE THREAD

**Issue by su832665** [topcoder-platform/qa-fun#134]
Steps to reporduce

1. Enter https://www.topcoder.com/contact-us/
2. Enter phone number >10 digits
3. Enter rest of the mandatory field 
4. Click on submit button
Expected result: Phone number field limit should be enabled as user typed more than 10 digit it should show an alert message
Actual: Not showing any error or alert message
Browser version: chrome 80.00
![image](https://user-images.githubusercontent.com/49670274/78256678-7cb21f80-7516-11ea-8030-9e854452ad1d.png)

**Comment by winterflame** [comment]
functional bug
