### ISSUE TITLE
Click Community link the highlighting arrow is not showing properly

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/qa-fun#136]
**screen shot**
![Screenshot (124)](https://user-images.githubusercontent.com/29044523/78256705-876cb480-7516-11ea-8f73-4168998e4274.png)

**screen cast**

[Uploading bandicam 2020-04-02 19-12-54-621.zip…]()

**Reproduction Steps:**

1. Go to https://www.topcoder.com/
2. Click Community link on header navigation
3. Observe the arrow mark should be below the Community link

**Expected Result:**
The arrow mark should be below community link
**Actual Result:**
the arrow mark is not below community link

**Device/OS:** Laptop | Windows 8.1

**Browser Information:** Google Chrome 80.0.3987.149

**Comment by winterflame** [comment]
dupe with #120
