### ISSUE TITLE
Mobile number field is taking multiple numbers (Length is not defined)

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#137]
Bug Title - Mobile number field is taking multiple numbers (Length is not defined)

Steps To Reproduce -

1. Go to https://www.topcoder.com/public
2. Now fill the phone number it will take as many numbers you will enter

Actual Result - The length is not defined and taking infinite numbers

Expected Result - It should take the defined length of number

Device/OS/Browser Information: Laptop HP, Windows10, ChromeVersion 80.0.3987.149

![Phone number](https://user-images.githubusercontent.com/42939505/78257404-6b1d4780-7517-11ea-8ab6-52f72856a5a7.png)

**Comment by winterflame** [comment]
Functional bug.
