### ISSUE TITLE
Text given in hero-video-block is not responsive. [Firefox]

### ISSUE THREAD

**Issue by AyushiGit12** [topcoder-platform/qa-fun#138]
Bug Title: Text given in hero-video-block is not responsive.
Steps to Reproduce :
1. Go to https://www.topcoder.com/ in mobile view
2. Check the text: 'Your On-Demand Remote Workforce Avoid disruption. Keep executing.'  should be properly aligned and responsive in various mobile views.

**Expected Result:**
The given text in the hero-video-block div should be properly aligned as we view it in different screen modes.
Actual Result:
The text is not properly aligned. Does not look neat when viewed in mobile view [Galaxy S9]

Screenshots:
![notAlignedText](https://user-images.githubusercontent.com/63055143/78256677-7c198900-7516-11ea-8d9a-46cb44873cf2.JPG)

Device/OS/Browser Information:
HP Laptop, Firefox Browser Version 74.0 (64-Bit)

**Comment by winterflame** [comment]
mobile view is out of scope
