### ISSUE TITLE
Search button is enabled even after the searchbox is empty

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/qa-fun#14]
![Screenshot (97)](https://user-images.githubusercontent.com/29044523/75689755-bd283e80-5cc7-11ea-9db5-1c85a209c074.png)

Reproduction Steps:

- Open https://www.topcoder.com and Login as a valid user
- Go to https://www.topcoder.com/challenges
- Check the search Challenges button is enabled even the search text box is empty
- Click  nothing happenes but a get request is hit.

Expected Result: search icon should be disabled

Actual Result: search icon button is enabled 

Device/OS: Laptop | Windows 8.1

Browser Information: Google Chrome 80.0.3987.116

**Comment by winterflame** [comment]
It's as designed.

**Comment by Vips19** [comment]
@winterflame There is even a GET request happening on click of search.. Is this also expected?

**Comment by winterflame** [comment]
@Vips19 That's fine - the search functionality is not broken.

**Comment by Vips19** [comment]
@winterflame  Ok thanks
