### ISSUE TITLE
Content alignment problem

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/qa-fun#146]
**Steps to Reproduce:**

1.Go to: https://www.topcoder.com/
2. Go to: https://www.topcoder.com/enterprise-offerings/
3. Observe
**Expected Result:**
There should proper content alignment in the page
**Actual Result:**
There is no proper content alignment with the text
![align](https://user-images.githubusercontent.com/37167721/78258826-731fbc00-7504-11ea-9702-6ba06b74ed2d.jpg)

****Environment:**** Chrome:Version 80.0.3987.149

**Comment by winterflame** [comment]
Not a problem
