### ISSUE TITLE
Description heading is overlapped [chrome]

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#149]
Bug title - Description heading is overlapped when we resize the window of browser

Steps To Reproduce -

1. Go to https://www.topcoder.com/
2. Now resize the window of browser by width at the smallest size
3. Scroll down and go to "our talent your success" part
4. Check developer section and observe their description heading is overlapped

Actual Result - Description heading is overlapped

Expected Result - It must be clearly visible at any window size 

Device/OS/Browser Information: Laptop HP, Windows10, ChromeVersion 80.0.3987.149

![Developers](https://user-images.githubusercontent.com/42939505/78259032-bf292b80-7519-11ea-8960-db582d2aecae.png)

**Comment by winterflame** [comment]
Only standard window size is in scope.
