### ISSUE TITLE
Web [Firefox] Alignment issues on Outline of tags

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#151]
Bug Title: Alignment Issue on Outline of tags
Steps to Reproduce:
1.Go to https://www.topcoder.com/
2.Click on Community
3. Select Competitive Programming under How it works Pages
4.View the tags in SRM 308 article
Expected Result:
Text on tags should appear Inside of the tags
Actual Result:
Text on tags appearing outside of the tags
Screenshots or screencast:[Error 3.zip](https://github.com/topcoder-platform/qa-fun/files/4421560/Error.3.zip)
Device/OS/Browser Information:
Firefox:74.0 (64-bit) Windows 7

**Comment by winterflame** [comment]
Thrive pages are not in scope.
