### ISSUE TITLE
Heading is not visible [Chrome]

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#153]
Bug title - Heading is not completely visible when we resize the window of the browser

Steps To Reproduce -

1. Go to https://www.topcoder.com/
2. Now resize the window of browser by width at the smallest size
3. Scroll down and go to "our talent your success" part
4. Select the Data Scientist section and observe their description heading is not completely visible

Actual Result - Description heading is not completely visible

Expected Result - It must be clearly visible at any window size

Device/OS/Browser Information: Laptop HP, Windows10, ChromeVersion 80.0.3987.149

![Data Sceintist](https://user-images.githubusercontent.com/42939505/78259496-6ad27b80-751a-11ea-8c56-19e5d9fcb844.png)

**Comment by winterflame** [comment]
Only standard window size is in scope.
