### ISSUE TITLE
Heading is not Visible in QA Engineer Tab [Chrome]

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#154]
Bug title - Heading is not completely visible in  QA Engineer Tab when we resize the window of the browser

Steps To Reproduce -

1. Go to https://www.topcoder.com/
2. resize the window of browser by width at the smallest size
3. Scroll down and go to "our talent your success" part
4. Select the QA Engineer section and observe their description heading is not completely visible

Actual Result - Description heading is not completely visible

Expected Result - It must be clearly visible at any window size

Device/OS/Browser Information: Laptop HP, Windows10, ChromeVersion 80.0.3987.149

![Engineers](https://user-images.githubusercontent.com/42939505/78259808-ca308b80-751a-11ea-902a-45c7249d39ca.png)

**Comment by winterflame** [comment]
Only standard window size is in scope.
