### ISSUE TITLE
Text Alignment/Typo error 

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#158]
Bug Title: Text Alignment/Typo error 
Steps to Reproduce:
1.Go to https://www.topcoder.com/
2.Click on Community
3. Scroll down under Overview Page 
4.View Earn with us Section under We are a global community of inspired and talented individuals heading
Expected Result:
Space should be there between words "a" and "typical"
Actual Result:
No Space between words "a" and "typical"
Screenshots or screencast:
[Error-3.zip](https://github.com/topcoder-platform/qa-fun/files/4421643/Error-3.zip)

Device/OS/Browser Information:
Chrome: Version 80.0.3987.162 (Official Build) (64-bit)
 Windows 7

**Comment by winterflame** [comment]
![Error-3](https://user-images.githubusercontent.com/4590317/78550177-34587180-7836-11ea-9729-c189b7c314e3.PNG)

**Comment by winterflame** [comment]
Not a bug.
