### ISSUE TITLE
Filter is getting applied on opening https://www.topcoder.com/challenges

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/qa-fun#16]
[bandicam 2020-03-02 21-21-36-802.zip](https://github.com/topcoder-platform/qa-fun/files/4276305/bandicam.2020-03-02.21-21-36-802.zip)

Reproduction Steps:

- Open https://www.topcoder.com and Login as a valid user
- Go to https://www.topcoder.com/challenges
- check the url it is redirecting to https://www.topcoder.com/challenges?filter[text]=Mechanics

Expected Result: It should go to https://www.topcoder.com/challenges
Actual Result: It redirected to https://www.topcoder.com/challenges?filter[text]=Mechanics

Device/OS: Laptop | Windows 8.1

Browser Information: Google Chrome 80.0.3987.116

**Comment by winterflame** [comment]
duplicated with #4

**Comment by Vips19** [comment]
@winterflame I faced this issue not only after entering any challenge and coming back. This issue happened even after I logged out and tried opening the challenge page.. the filter was getting applied

**Comment by winterflame** [comment]
@Vips19 It looks similar to ticket 4. I'll reopen this one.

**Comment by Vips19** [comment]
@winterflame Yes I can understand it's simlar issue. But just wanted you to know.

**Comment by winterflame** [comment]
@Vips19 Thank you!
