### ISSUE TITLE
Data science toggle button shows inaccurate challenges when clicked 

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/qa-fun#17]
1. Go to:https://www.topcoder.com/challenges?bucket=reviewOpportunities&filter[tracks][design]=true&filter[tracks][develop]=true
2. On the right side, click the Data science toggle button
3. After that click and  observe the challenges displayed and challenges count 

**Expected Result:** The Data science button should display data science challenges when clicked
**Actual Result:** Data science toggle button fails to display data science challenges, when is enabled alone

**Device/OS:** Laptop | linux (32bit)
[datascience.zip](https://github.com/topcoder-platform/qa-fun/files/4276355/datascience.zip)

**Browser Information:** Firefox Version 73.0.1 (32-bit)

**Comment by winterflame** [comment]
Not a bug - the count on the top right is for challenges amount, not review opportunities.
