### ISSUE TITLE
Underline of  BACK TO ENTERPRISE OFFERINGS is disappearing when user mouse hover over the link

### ISSUE THREAD

**Issue by su832665** [topcoder-platform/qa-fun#170]
Steps to reproduce
1.	Enter https://www.topcoder.com/enterprise-offerings/contact/
2.	Mouse hover over BACK TO ENTERPRISE OFFERINGS link

Expected result: Underline should not disappear
Actual: Underline of  BACK TO ENTERPRISE OFFERINGS is disappearing when user mouse hover over the link
Browser version: chrome 80.00
![image](https://user-images.githubusercontent.com/49670274/78266943-0d432c80-7524-11ea-9f59-5fd37cd60a1d.png)

![image](https://user-images.githubusercontent.com/49670274/78266982-18965800-7524-11ea-9b34-089fad6523e7.png)

**Comment by winterflame** [comment]
not a bug, it's as designed
