### ISSUE TITLE
Two notifications appearing near review score card link

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#172]
Bug Title: Two notifications appearing near review score card link
Steps to Reproduce:
1.Go to https://www.topcoder.com
2.Click Community>Compete>All challenges
3.Select Topcoder QA Fun Challenge Series 10 - Understanding UI Testing with Topcoder and hover mouse over question mark near review Scorecard link
Expected Result:
Only one notification should appear
Actual Result:
Two notifications appearing on hovering mouse over question mark near review scorecard
Screenshots or screencast:
[Error 4.zip](https://github.com/topcoder-platform/qa-fun/files/4421961/Error.4.zip)

Device/OS/Browser Information:
Chrome Version 80.0.3987.162 (Official Build) (64-bit) windows 7

**Comment by winterflame** [comment]
cannot reproduce
