### ISSUE TITLE
System is allowing user to enter charecters in phone number field in download ebook form

### ISSUE THREAD

**Issue by su832665** [topcoder-platform/qa-fun#175]
Steps to reproduce
1.	Enter https://www.topcoder.com/qa
2.	Enter characters in phone number field 
3.	Enter rest of the mandatory field
4.	Click on submit button
Expected result: System should not allow user to enter charecters in phone number field s
Actual: System is allowing user to enter charecters in phone number field in download ebook form
Browser version: chrome 80.00
![image](https://user-images.githubusercontent.com/49670274/78268513-eab21300-7525-11ea-9f4b-4e56a4a9a67f.png)

**Comment by winterflame** [comment]
functional bug
