### ISSUE TITLE
Should show notice message after input some spaces in "Find a service" search box

### ISSUE THREAD

**Issue by tranglee205** [topcoder-platform/qa-fun#176]
**Steps to Reproduce:**
1. Open https://www.topcoder.com and Login as a valid user
2. Go to any challenges (E.g: https://www.topcoder.com/challenges/30119394)
3. On details tab, Click on "+" icon inside "Share" area
4. Try to enter some spaces in "Find a service" search box
5. Observe the result.

**Expected Result:**
Should show notice message after input some spaces in "Find a service" search box.

**Actual Result:**
"Top services" still show. Only "Load more" button is disappeared after input some spaces.

**Screenshots or screencast:**
https://www.screencast.com/t/fW7WYtZAX

**Device/OS/Browser Information:** Surface Laptop | Window 10 | Chrome 80.0.3987.162 
Firefox 74.0

**Comment by winterflame** [comment]
functional bug
