### ISSUE TITLE
Unlimited text allowed in 'First name' entry on Contact page

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/qa-fun#177]
Steps to Reproduce:
Open -> https://www.topcoder.com/
Got to -> More -> Contact Us -> Open page
Notice user is able to enter unlimited characters
Expected Result:
There should be a limit set for entering characters in 'First Name' field.
Actual Result:
User is able to enter unlimited characters
Screenshots or screencast:

Device/OS/Browser Information:
Platform - Windows 10
Device - HP ProBook 440G6
Microsoft Windows 10 Enterprise
Version
10.0.17763 Build 17763

![image](https://user-images.githubusercontent.com/12671119/78268954-94919f80-7526-11ea-8a1f-4d6d659be5b1.png)

**Comment by winterflame** [comment]
This is a functional bug.
