### ISSUE TITLE
There is 'Prev' and 'Next' button also given in the images which are not working

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/qa-fun#180]
Steps to Reproduce:
Open -> https://www.topcoder.com/
Got to -> https://www.topcoder.com/case-studies/macys/
Notice there is 'Prev' and 'Next' button also given in the images which are not working.
Only arrows highlighted with green circle are working.
Expected Result:
There should not be additional buttons displayed in the image which can confuse a user.
Actual Result:
There is 'Prev' and 'Next' button also given in the images which are not working.
Only arrows highlighted with green circle are working.

Screenshots or screencast:

![image](https://user-images.githubusercontent.com/12671119/78269796-ae7fb200-7527-11ea-90ed-248c82645327.png)

Device/OS/Browser Information:
Platform - Windows 10
Device - HP ProBook 440G6
Microsoft Windows 10 Enterprise
Version
10.0.17763 Build 17763

**Comment by winterflame** [comment]
not a bug
