### ISSUE TITLE
When user is clicked on back to topcoder.com user is navigating to enterprise workforce transormation page in new window

### ISSUE THREAD

**Issue by su832665** [topcoder-platform/qa-fun#182]
Steps to reproduce
1.	Enter https://www.topcoder.com/qa
2.	CLick on back to topcoder.com button
3.	check the page navigation

Expected result: User should navigate to topcoder home page in the same window
Actual: user is navigating to enterprise workforce transormation page in new window
Browser version: chrome 80.00

![image](https://user-images.githubusercontent.com/49670274/78270603-aaa05f80-7528-11ea-99ed-63baaebd0ac7.png)
![image](https://user-images.githubusercontent.com/49670274/78270641-b855e500-7528-11ea-96d8-645a059a54d8.png)

**Comment by winterflame** [comment]
functional bug
