### ISSUE TITLE
The collapse button overlaps the text on medium screens in the web!

### ISSUE THREAD

**Issue by ZafrKhan** [topcoder-platform/qa-fun#183]
Steps to reproduce:
Go to https://www.topcoder.com/thrive/articles/UI%20Testing%20Explained
Restore down the screen at the top of the page. Click on Explore button.
Expected Result:
The content behind the list is supposed to slide up and down with the list itself for a collapse button
Actual Result:
The list overlaps the text and images behind the list.
![Firstimage](https://user-images.githubusercontent.com/63061847/78271590-f69fd400-7529-11ea-957c-0e9c2a1f464f.jpg)
![Secondimage](https://user-images.githubusercontent.com/63061847/78271601-facbf180-7529-11ea-9d62-4efe2d01c533.jpg)
Laptop/Windows 10/Google Chrome Version 80.0.3987.162

**Comment by winterflame** [comment]
Only normal window size is in scope.
