### ISSUE TITLE
Lot of Gap in between "KEEP DIGITAL AND TECHNOLOGY EXECUTION STRONG" and next topic or frame "Our Talent Your success"

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#184]
Hi Team,

Guess so much space in between is not needed - alignment to be done between 
 "KEEP DIGITAL AND TECHNOLOGY EXECUTION STRONG" and next topic or frame "Our Talent Your success"
Bug Title: <Irregularity in the display in the home page>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Scroll down to the bottom of the home page 
3. Check this alignment - Lot of Gap in between "KEEP DIGITAL AND TECHNOLOGY EXECUTION STRONG" and next topic or frame "Our Talent Your success
Expected Result:
<Alignment should be proper with less space>
Actual Result:
<Lot of Gap in between "KEEP DIGITAL AND TECHNOLOGY EXECUTION STRONG" and next topic or frame "Our Talent Your success>
Screenshots or screencast:
![Issue1_gnjs](https://user-images.githubusercontent.com/63063841/78273008-e12ba980-752b-11ea-9fe0-daf13e329d21.jpg)
Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
Incomplete
