### ISSUE TITLE
Profile logo and username disappears on restoring the screen to medium scale

### ISSUE THREAD

**Issue by ZafrKhan** [topcoder-platform/qa-fun#185]
Steps to Reproduce:
Go to the URL: https://www.topcoder.com/thrive/articles/UI%20Testing%20Explained
Restore down the screen and the profile logo and name will be missing
Expected Result:
It is supposed to show the user at least the username or an icon indicating profile.
Actual Result:
It just comes down to show an arrow mark(down pointing arrow)
Device Information:
Laptop/Windows 10/Google Chrome Version 80.0.3987.162

![Fourthimage](https://user-images.githubusercontent.com/63061847/78273368-59926a80-752c-11ea-97e3-f11a1a760aee.jpg)

**Comment by winterflame** [comment]
Only normal window size is in scope.
