### ISSUE TITLE
On Page Scroll down - Menu Sub menu should not get hidden.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#187]
Steps : -

1.Hit URL - https://www.topcoder.com/
2.Login with topcoder credentials.
3.Now scroll down /page down using mouse.

Expected Result : All the menu and sub menu should not hidden on page scroll down
Actual Result : All the menu and sub menu gets hidden.

Note : This can be taken example from Facebook or any other web application where on page scroll
Menu and SubMenu should not get hidden on page scroll.It should be at the top of the page everytime.

Browser : Chrome 80

![image](https://user-images.githubusercontent.com/61318135/78274255-8f841e80-752d-11ea-9155-c7cc42a0aa7d.png)

**Comment by winterflame** [comment]
not a bug

**Comment by winterflame** [comment]
@ab668685 "Not a bug" means the feature is working as expected.
