### ISSUE TITLE
Toggle tags are disable in review-opportunity challenges page

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/qa-fun#19]
**Step to reproduce**
1. Go to the topcoder page and login with valid user.
2. Go to https://www.topcoder.com/challenges?bucket=reviewOpportunities page
3. Tap on the days to apply and observe review page tags below the challenge heading

**Expected Result**
Tags below the challenge heading of review opportunity page should works as button

**Actual page** 
Review opportunity page tags are disabled 

**Screenshot**
https://drive.google.com/open?id=1oSZTNF-BbZ-kowo1S-K7W1gdr817lNMp

**OS /Device info** 
Lenovo Thinkpad, Windows 10 pro

**Browser Info**
Firefox 73.0.1

**Comment by winterflame** [comment]
Not a bug.
