### ISSUE TITLE
Text color coming as white with white background for icon titles under Our Talent, Your Success section in iPad mode

### ISSUE THREAD

**Issue by AyushiGit12** [topcoder-platform/qa-fun#190]
Bug Title: Text color coming as white with white background for icon titles under Our Talent, Your Success section in iPad mode
Steps to reproduce:
1. Go to https://www.topcoder.com/
2. Scroll down to Our Talent Your Success section
3. Switch to iPad responsive mode under Inspect Element
4. Observe the icon title getting disappeared on clicking the icons ( Developer, Designer, Data Scientist, etc.). Note: The title text color is clashing with the white background.

Expected Result: The icon title should be visible on clicking that icon
Actual Result: The icon title is not visible because of the white color CSS assigned to it.

Screenshot:

![textGettingDissapeared](https://user-images.githubusercontent.com/63055143/78275126-d45c8500-752e-11ea-94b6-7f31970e6dbc.JPG)

Device/OS/Browser Information:
Laptop, Windows 10 Firefox  Version 74.0

**Comment by winterflame** [comment]
Not in scope
