### ISSUE TITLE
Topcoder icon is black and onclick of Topcoder icon its not moving to home/top page

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#192]
Steps : -

1.Hit URL - https://www.topcoder.com/
2.Login with topcoder credentials.
3.Now scroll down.
4. Click on the below topcoder icon below >> QUESTIONS? CONTACT US

Expected Result : On click of topcoder icon it should take user to home page /top of the page
Actual Result :Topcoder icon is black and onclick of Topcoder icon its not moving to home/top page.

Suggestion : When user scroll down of the page ,there should be scroll up icon button .
Browser : Chrome 80

![image](https://user-images.githubusercontent.com/61318135/78275847-cce9ab80-752f-11ea-9a3a-92618aa141d0.png)

**Comment by winterflame** [comment]
not a bug

**Comment by winterflame** [comment]
@ab668685 "Not a bug" means the feature is working as expected.
