### ISSUE TITLE
Back button is disabled after going to Contact Page via More->Contacts

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#194]
Hi Team,
Please check this:
Back button is disabled after going to Contact Page via More->Contact
Back button should be enabled to go back from the Contact page from where it is selected

Bug Title: <Back button is disabled after going to Contact Page via More->Contacts>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Click the More button and select Contacts
3. Contact page opens 
4. Try clicking the back button and you cannot go back
Expected Result:
<clicking the back button should take you back>
Actual Result:
<Back button is disabled after going to Contact Page via More->Contacts>
Screenshots or screencast:
![Issue5_gnjs](https://user-images.githubusercontent.com/63063841/78276723-0ff84e80-7531-11ea-89a3-3fc0a3506cb7.jpg)
Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
incomplete
