### ISSUE TITLE
On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse(Solutions)

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#196]
Hi Team,
Please check this:
On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse
Hi Team,
Please check this:
On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse

Bug Title: <On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse(Solutions)>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Click the Company,Solutions, Enterprise on the home screen to show more options
3. Hover the mouse on the options
Expected Result:
<on hovering the mouse should highlight or select them without clicking the mouse(Solutions)>
Actual Result:
<on hovering the mouse does not highlight or select them without clicking the mouse(Solutions)>
Screenshots or screencast:
![Issue7_gnjs](https://user-images.githubusercontent.com/63063841/78277337-f6a3d200-7531-11ea-9ab6-c80dad071a31.jpg)

Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
similar to #195
