### ISSUE TITLE
Blog image seem multiple time

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/qa-fun#197]
**Steps to Reproduce:**

    Go to the topcoder URL- https://www.topcoder.com/ready-set-golang/
    Observe blog header image seem multiple time

**Expected Result:**
Blog header should not multiple time, same image repeated is not useful in informative page

**Actual Result:**
Header image seem multiple time in blog

**Screenshots or screencast:**
![image](https://user-images.githubusercontent.com/23450398/78277302-ea1f7980-7531-11ea-933c-99ef9355f21c.png)

**Device/OS/Browser Information:**
Lenovo Thinkpad, Windows 10 Pro, Chrome  80.0.3987.162

**Comment by winterflame** [comment]
Not a bug - one is the banner and another is in the body part.
