### ISSUE TITLE
On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse(Enterprise)

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#198]
Hi Team,
Please check this:
On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse

Bug Title: <On Clicking the Company,Solutions, Enterprise on the home screen which displays more options but on hovering the mouse does not highlight or select them without clicking the mouse(Enterprise)>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Click the Company,Solutions, Enterprise on the home screen to show more options
3. Hover the mouse on the options
Expected Result:
<on hovering the mouse should highlight or select them without clicking the mouse(Enterprise)>
Actual Result:
<on hovering the mouse does not highlight or select them without clicking the mouse(Enterprise)>
Screenshots or screencast:
![Issue8_gnjs](https://user-images.githubusercontent.com/63063841/78277401-12a77380-7532-11ea-8b59-370c8943b94e.jpg)

Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
similar to #195
