### ISSUE TITLE
Enterprise Security >> GET YOUR FREE ENTERPRISE ADOPTION PLAYBOOK HERE (link). >> On Click of Topcoder button it redirects to new window of topcoder.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#202]
Steps : -

1.Hit URL - https://www.topcoder.com/
2.Login with topcoder credentials.
3.Click on Enterprise Menu >> Sub menu >> Enterprise Security
4. Scroll down.
5. Click on GET YOUR FREE ENTERPRISE ADOPTION PLAYBOOK HERE (link).
6. It redirect user to - https://www.topcoder.com/openassemblyreport
7. Click on Back to Topcoder button.

Expected Result : On Click of Topcoder button it should not redirect to new window .Topcoder page should open in same window
Actual Result : On Click of Topcoder button it redirects to new window of topcoder.

**Comment by winterflame** [comment]
functional bug
