### ISSUE TITLE
Buttons are not highlighted like the below on hovering the mouse

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#207]
Hi Team,

Kindly check the buttons are not highlighted 
Buttons are not highlighted like the below on hovering the mouse
Access Top Talent 
Explore our community

Bug Title: <Buttons are not highlighted like the below on hovering the mouse>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Scroll down a little tillt the page till the I m Customer box
3. Check these buttons are not highlighted on hovering the mouse
Expected Result:
<buttons should be highlighted on hovering the mouse>
Actual Result:
<buttons are not highlighted on hovering the mouse>
Screenshots or screencast:
![Issue10_gnjs](https://user-images.githubusercontent.com/63063841/78289262-8308c180-753f-11ea-98db-71b271bc2783.jpg)
Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
incomplete
