### ISSUE TITLE
Resources page is not responsive in Firefox

### ISSUE THREAD

**Issue by AyushiGit12** [topcoder-platform/qa-fun#209]
Bug Title: Resources page is not responsive in Firefox
Steps to Reproduce:
1. Go to  https://www.topcoder.com/
2. In the navbar, options select More 
3. dropdown will open select Resources option 
4. Open Resources page in the mobile view and verify whether the categories given on the page are responsive.

Expected Result: The entire Resources page should be responsive.
Actual Result: Page is not responsive.

Screenshot:
![image](https://user-images.githubusercontent.com/63055143/78290727-cd8b3d80-7541-11ea-8bdd-ba08d3e626d5.png)

Device/OS:
Laptop | Windows 10 (64bit)

Browser Information:
Mozilla Firefox Version 74.0

**Comment by winterflame** [comment]
mobile view is out of scope
