### ISSUE TITLE
[web-Firefox] Alignment issue 

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#210]
Bug Title: Alignment issue 
Steps to Reproduce:
1.Go to https://www.topcoder.com
2.Click Community and scroll down the page
3.Click "Learn more" button under Topcoder in the time of Covid-19
4.Scroll down the page and click Perks of remote work: the craziest places to work from link under Topcoder nation heading
5.View the section under Related posts

Expected Result: Bottom of the Section should be uniformly aligned

Actual Result: Bottom of the Section is not uniformly aligned

Screenshots or screencast:

[Error 6.zip](https://github.com/topcoder-platform/qa-fun/files/4423290/Error.6.zip)

Device/OS/Browser Information:
Firfox 74.0 (64-bit) windows 7

**Comment by winterflame** [comment]
![Error 6](https://user-images.githubusercontent.com/4590317/78551040-a67d8600-7837-11ea-9fbd-8809d02d117d.jpg)
