### ISSUE TITLE
[web-chrome] Site can't be reached error on clicking link

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#211]
Bug Title: <Site can't be reached error on clicking link>
Steps to Reproduce:
1. Go to https://tco20.topcoder.com/competition-rules
2.Scroll down the page and click www.software.topcoder.com under the heading TERMINATION/EXCLUSION
Expected Result:
Site can't be reached error is appearing on clicking the link
Actual Result:
Site should be loaded on clicking link
Screenshots or screencast:
[Error 7.zip](https://github.com/topcoder-platform/qa-fun/files/4423442/Error.7.zip)

Device/OS/Browser Information:
Chrome Version 80.0.3987.162 (Official Build) (64-bit) windows 7

**Comment by winterflame** [comment]
functional bug
