### ISSUE TITLE
Looks this part out of contrast

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#213]
Team,
Check this:
Looks this part out of contrast
Bug Title: <Looks this part out of contrast>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Scroll down to the bottom of the page till the end till you rreach our customers
3. Check this picture colour contrast
Expected Result:
<This part should be in contrast>
Actual Result:
<This part is out of contrast>
Screenshots or screencast:
![Issue11_gnjs](https://user-images.githubusercontent.com/63063841/78301760-2f09d700-7557-11ea-8aa3-885512aaad92.jpg)
Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
incomplete
