### ISSUE TITLE
Looks like a non responsive design for this 

### ISSUE THREAD

**Issue by gnjoshuasamuel** [topcoder-platform/qa-fun#214]
Hi Team,
Kindly check this Looks like a non responsive design for this 
Bug Title: <Looks like a non responsive design for this>
Steps to Reproduce:
1. Navigate to https://www.topcoder.com/
2. Scroll down to the bottom of the page till the end where you can find this picture
3. Check this non responsive design
Expected Result:
<Design response should be good>
Actual Result:
<Design response is not good>
Screenshots or screencast:
![Issue12_gnjs](https://user-images.githubusercontent.com/63063841/78302071-c2430c80-7557-11ea-8ec4-39ffcf960de0.jpg)
Device/OS/Browser Information:
<Dell, Windows 10 and Chrome>

**Comment by winterflame** [comment]
incomplete
