### ISSUE TITLE
[Web-Firefox] In Date Range Start Date Is Accepting Future Date

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#22]
1. Go To https://www.topcoder.com/challenges

2. Click On Filters

3. Click On Date Range > Click On Start  Date & Try To Add Future Date Then Observe

4. See Screencast
[Date Range.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/4276859/Date.Range.mp4.zip)

5. Expected Result: It Should Not Accept Start Date As Future Date

6. Actual Result: Its Accepting Start Date As Future Date

7. Device: Laptop

8. OS: MacOs
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4276869/Mac.Version.png.zip)

9. Browser:
[Firefox Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4276870/Firefox.Version.png.zip)

**Comment by winterflame** [comment]
Not a bug.
