### ISSUE TITLE
[UI Issue][Chrome][Win10]In "SRMS", there is just one item but not centered.

### ISSUE THREAD

**Issue by fanwenlin** [topcoder-platform/qa-fun#222]
Bug Title: In "SRMS", there is just one item but it's not centered.
Steps to Reproduce:
1. Login
2. Go to https://www.topcoder.com/my-dashboard
3. Click "SRMS"
Expected Result:
There is just one item below, so it should be centered.
Actual Result:
It's not centered.
Screenshots or screencast:
![image](https://user-images.githubusercontent.com/17265932/78348299-5fdc2180-75d4-11ea-9ac1-8c5226f4e4a1.png)

Device/OS/Browser Information:
OS: Windows 10 Enterprise 19035.1000
Browser: Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by winterflame** [comment]
not a bug

**Comment by winterflame** [comment]
Looks like challenges in "My communities" tab are center aligned, reopen it.
