### ISSUE TITLE
'Resource' selection from menu item doesn't show any content

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/qa-fun#224]
Steps to Reproduce:
1. Open -> https://www.topcoder.com/
2. Click on 'More' -> Select 1st item in the menu i.e. Resource.
3. No new page or content will open although 'Resource' word will appear highlighted with green color
 
Expected Result:
Resource selection from menu should display some different content related to resource.

Actual Result:
No new page or content will open when user clicks on 'Resource' although 'Resource' word will appear highlighted with green color

Screenshots or screencast:

![image](https://user-images.githubusercontent.com/12671119/78349934-fa7f3500-75c1-11ea-8b3f-0f22fb3207ea.png)

Device/OS/Browser Information:
Platform - Windows 10
Device - HP ProBook 440G6
Microsoft Windows 10 Enterprise
Version
10.0.17763 Build 17763

**Comment by winterflame** [comment]
Cannot reproduce - it links to https://www.topcoder.com/resources/
