### ISSUE TITLE
Video is not loading in Business tab 

### ISSUE THREAD

**Issue by sridevinagaraj** [topcoder-platform/qa-fun#229]
Steps To Reproduce -

1. Go to https://www.topcoder.com/
2. Click Business tag
3. Click  "YOUR ON-DEMAND REMOTE WORKFORCE
AVOID DISRUPTION. KEEP EXECUTING." video 
4. Press play
5. Click 1.45 min of the video 
Video is not loading.Loader also not visible.

![issue1](https://user-images.githubusercontent.com/25819254/78378782-18af5a00-75ef-11ea-8177-d3eabb9b709f.PNG)

**Comment by winterflame** [comment]
This is a functional bug, not UI bug.
