### ISSUE TITLE
Failed to save the filter

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#23]
**Steps to Reproduce:**
1. Go to https://www.topcoder.com/challenges
2. Click on "Filters" at the right side.
3. From Subtrack drop down select "BugHunt"
4. Select Start date and End date 
5. Click on Save filter

**Expected Result:**
Filter should be saved without any error

**Actual Result:**
Failed to save the filter

**Screenshots or screencast:**
Video attached as zip format

[Issue1.zip](https://github.com/topcoder-platform/qa-fun/files/4276925/Issue1.zip)

![Issue1_screenshot](https://user-images.githubusercontent.com/51490878/75701612-1600d280-5cda-11ea-9f03-e5d950407dec.png)

![BrowserInfo_Chrome_ 80 0 3987 116](https://user-images.githubusercontent.com/51490878/75701644-22852b00-5cda-11ea-90b9-d9701ac4ed06.png)

![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/75701690-33ce3780-5cda-11ea-9a87-2fa6a65e07c5.png)

Device/OS/Browser Information:
Windows 10,
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
#2
