### ISSUE TITLE
Email validation  not happening at Covid-19 "WE'RE HERE TO HELP" Form 

### ISSUE THREAD

**Issue by sridevinagaraj** [topcoder-platform/qa-fun#230]
Email validation and none of the field data validation 
not happening at Covid-19 "WE'RE HERE TO HELP" Form.

Steps to reproduce,
1.Click https://www.topcoder.com/covid-19/
2. File  "WE'RE HERE TO HELP" Form and submit

success message also disappearing in very short span after submitting.

![issue2](https://user-images.githubusercontent.com/25819254/78379855-a770a680-75f0-11ea-8068-f4600bee8ad6.PNG)

**Comment by sridevinagaraj** [comment]
Similarly Contact us page form as well
![issue3](https://user-images.githubusercontent.com/25819254/78380682-ddfaf100-75f1-11ea-99a9-dd1171d21f9e.PNG)

**Comment by winterflame** [comment]
It's functional bug, not UI bug, also please follow the template in the challenge detail to report bugs.
