### ISSUE TITLE
"Get the RSS feed" page is not available correctly

### ISSUE THREAD

**Issue by kalindipandey** [topcoder-platform/qa-fun#233]
**URL:**
https://www.topcoder.com/challenges?
http://feeds.topcoder.com/challenges/feed?list=active&contestType=all

**Reproduction Steps:**

Open https://www.topcoder.com and Login as a valid user
Go to https://www.topcoder.com/challenges/?
Click on "Get the RSS feed"

**Expected Result:**  RSS feed page should open with a normal behaviour 

**Actual Result:**  RSS feed page is not available and page has the message "This XML file does not appear to have any style information associated with it. The document tree is shown below."

**Device/OS**: Laptop | macOS | Version: 10.13.4

**Browser Information**: Google Chrome Version : 80.0.3987.149

**Screenshot** 

<img width="1440" alt="issue_1" src="https://user-images.githubusercontent.com/46349625/78464344-cc0a7280-7705-11ea-9a27-6f21a69d52fc.png">

**Comment by winterflame** [comment]
Not UI bug
