### ISSUE TITLE
Empty grey div

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#235]
Url: https://www.topcoder.com/public-sector/public-sector-contact/

Reproduction Steps:

- Open https://www.topcoder.com/public-sector/public-sector-contact/

Expected Result: Either div should not be visible or should have content

Actual Result: Empty div

Device/OS: Windows 10 | Firefox Latest version

![Screenshot_2020-04-05 Public Sector Contact Topcoder(1)](https://user-images.githubusercontent.com/32861951/78473495-abbad200-775e-11ea-971c-f72b6084adb0.png)

**Comment by winterflame** [comment]
not a bug
