### ISSUE TITLE
Unaligned checkbox

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#236]
Url: https://www.topcoder.com/public-sector/public-sector-contact/

Reproduction Steps:

- Open https://www.topcoder.com/public-sector/public-sector-contact/

Expected Result: Checkbox should be aligned with form

Actual Result: Checkbox is not aligned

Device/OS: Windows 10 | Firefox Latest version

![Screenshot_2020-04-05 Public Sector Contact Topcoder(2)](https://user-images.githubusercontent.com/32861951/78473562-46b3ac00-775f-11ea-8b1e-86ac9780a435.png)

**Comment by winterflame** [comment]
dupe with #206
