### ISSUE TITLE
Improper margin in case study

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/qa-fun#239]
**Steps to Reproduce:** 

1. Go to: https://www.topcoder.com/case-studies/macys/
2. Scroll down to 'The Challenge' and observe the text alignment.

**Expected Result:**
The text should have a proper margin.

**Actual Result:**
There is no margin to the left. 

![Screen Shot 2020-04-05 at 6 27 02 PM](https://user-images.githubusercontent.com/17943805/78498974-75378400-776b-11ea-9af6-e3ced987ee3f.png)

**Environment:** Chrome:Version 80.0.3987.149

**OS:** Mac OS

**Comment by winterflame** [comment]
cannot reproduce
