### ISSUE TITLE
[Web-Firefox] Failed to save filter pop-up opens

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#24]
Reproduction Steps:
1.Open https://www.topcoder.com and Login as a valid user
2.Go to https://www.topcoder.com/challenges
3.Click Filter
4.Select any Subtrack 
5.Click Save filter

Expected Result: Filter should be saved
[Save Filter Not enabled.zip](https://github.com/topcoder-platform/qa-fun/files/4276961/Save.Filter.Not.enabled.zip)

Actual Result: Failed to save option pop-up opens

Device/OS: Laptop | Windows 7
Browser Information: 73.0.1 (64-bit)

**Comment by winterflame** [comment]
duplicated with #2
