### ISSUE TITLE
Footer of the application have missing heading for sub topics.

### ISSUE THREAD

**Issue by prachiarora11** [topcoder-platform/qa-fun#248]
Steps to Reproduce:
Step1: Open the url https://www.topcoder.com/
Step2: Go to Footer of the page.
Step3: We can see heading and sub topics.

Expected Result:
Either line for the subtopics should be merged with other heading or a heading should be given.

Actual Result:
Heading such as: SOLUTIONS, ENTERPRISE,COMPANY,CONTACT US
For sub topics :Case Studies,Blog, Public Sector, FAQs there is no heading.

Screenshots or screencast:
![Bug4](https://user-images.githubusercontent.com/42865669/78723596-5f7fb580-7949-11ea-9683-ee2dbe650b4d.png)

Device/OS/Browser Information:  
iMac/macOS, Chrome Browser

**Comment by winterflame** [comment]
duplicated
