### ISSUE TITLE
Form validation errors.

### ISSUE THREAD

**Issue by prachiarora11** [topcoder-platform/qa-fun#250]
Steps to Reproduce:
Step1: Open the url https://www.topcoder.com/
Step2: Go to Company
Step3: Select Sponser TCO in sub tab.
Step4: Scroll down go to bottom of page.
Step5: Click on button Get Sponsorship Info
https://www.topcoder.com/sponsorship-info
Step6: Keep all form fields empty and submit the form.(error msg of form validation will be generated)
Step7: Fill all the details one by one except email field.
Step8: In email field keep any one letter.

Expected Result:
It should verify whether the email Id is valid or not.

Actual Result:
It does not verify email id is valid or not.
Also the error message becomes short after giving any one letter as input.

Screenshots or screencast:
![Bug6](https://user-images.githubusercontent.com/42865669/78723793-b9807b00-7949-11ea-8a6a-a500e3bdd23e.png)

Device/OS/Browser Information:  
iMac/macOS, Chrome Browser

**Comment by winterflame** [comment]
duplicated
