### ISSUE TITLE
Statistics page - CANNOT READ PROPERTY 'TOSTRING' OF UNDEFINED error message when loading page

### ISSUE THREAD

**Issue by aruam** [topcoder-platform/qa-fun#251]
Steps :
1 : Launch the application https://www.topcoder.com in firefox
2 : Click on "COMMUNITY" tab
3 : Observe Member count, Total prizes and completed challenges

Actual Result :
CANNOT READ PROPERTY 'TOSTRING' OF UNDEFINED error message

Expected Result :
Actual data should display.

Please note, this error is intermittent, but however it needs to be fixed

Screen Shot : https://monosnap.com/list/5e8dda009050d92ac0f69a68

Environment :
Device : Laptop HP
Operating system : Windows 10 (64 Bit)
Browser : Mozilla Firefox 74.0 (64 Bit)

**Comment by winterflame** [comment]
cannot reproduce
![stat](https://user-images.githubusercontent.com/4590317/78853982-d0f75b00-7a52-11ea-93c1-6d605a652105.jpg)
