### ISSUE TITLE
Rank column stays static in the Statistics page on sorting

### ISSUE THREAD

**Issue by aruam** [topcoder-platform/qa-fun#255]
Steps :
1 : Launch the application https://www.topcoder.com in firefox
2 : Click on "COMMUNITY" tab
3 : Click on Explore - > Statistics
4 : Navigate to General -> First place by country
5: Click on Sort button in country
6: Observe Rank

Actual Result :
Rank remains same, but countries list change.

Expected Result :
Rank should change in line with the countries sort list

Screen Shot :
<img width="960" alt="21" src="https://user-images.githubusercontent.com/4590317/78891805-ca8cd180-7a9a-11ea-9e36-3f5f4d1c3af1.PNG">

Environment :
Device : Laptop HP
Operating system : Windows 10 (64 Bit)
Browser : Mozilla Firefox 74.0 (64 Bit)

**Comment by winterflame** [comment]
It's not a bug - the RANK column is just for displaying the row numbers of the table.

**Comment by aruam** [comment]
As an end user I take it as an rank because without sorting on its original form it is like ranks...

Really surprised to know that rank column in the top coder with different country names list  is for displaying columns.....

If it was only an row number then the label can be named as row number or serial number not as rank

Regards,
Arunachalam L
________________________________

**Comment by winterflame** [comment]
@aruam OK, this column naming issue needs to be fixed.
