### ISSUE TITLE
[Usability] Download the Ebook link broken

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/qa-fun#257]
**Steps to Reproduce:** 
1. Go to the link https://www.topcoder.com/7TalentTrends
2. Scroll down to tap on Download the Ebook
3. Observe no download found

**Expected Result:** No broken link should be in page
**Actual Result:**  Found broken link Download the Ebook

**Screenshots or screencast:** 
![image](https://user-images.githubusercontent.com/23450398/80955088-3f45f800-8e1c-11ea-9647-363a3297a49f.png)

Device/OS/Browser Information: 
Lenovo Thinkpad, Windows 10, Firefox 75.0

**Comment by winterflame** [comment]
Functional bug.
