### ISSUE TITLE
Please Fix These Errors Popup cuts off 

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#258]
Steps:-
1 .Enter the URL - https://www.topcoder.com/
2. Click on WORK IS CHANGING See the 7 Most Important Trends in Enterprise Talent – FREE DOWNLOAD - link
3. Click on Download button without entering fields first name ,last name ...
4. View the error popup

Actual Result : Error popup cuts off in the page.

Expected Result : Popup should display completely/.

Browser - Chrome . Windows -10

![image](https://user-images.githubusercontent.com/61318135/80957530-f2185500-8e20-11ea-93db-6ce597de72e3.png)

![image](https://user-images.githubusercontent.com/61318135/80957518-eb89dd80-8e20-11ea-8652-061fdb6911b0.png)

**Comment by winterflame** [comment]
UI bug
