### ISSUE TITLE
[Web-Firefox] All Challenges & My Challenges Shows Different In Numbers

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#26]
1. Go To https://www.topcoder.com/challenges

2. See All Challenges Are Showing 82 & My Challenges Are Showing 5.

3. Click On Any Challenges Then Click On < Key & Go Back To Challenges Page.

4. Now Its Showing All Challenges As 44 & My Challenges As 3.

5. See Screencast & Observe.
[All Challenges.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/4277028/All.Challenges.mp4.zip)

6. Expected Result: All Challenges & My Challenges Number Should Be Same.

7. Actual Result: All Challenges & My Challenges Shows Different In Numbers

8. Device: Laptop

9. OS: 
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4277042/Mac.Version.png.zip)

10. Browser:
[Firefox Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4277045/Firefox.Version.png.zip)

**Comment by winterflame** [comment]
duplicated with #9
