### ISSUE TITLE
Firefox Version 74 - Topcoder Page is not loading .

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#261]
Steps:
1. Enter the URL : https://www.topcoder.com/ in Firefox browser  without login .
2. View the page.

Actual Result : Page is not completely loading ,neither footer of the page ,contact us ....

Expected Result : Page should load properly.

Browser -Firefox , Windows -10

![image](https://user-images.githubusercontent.com/61318135/80960448-81743700-8e26-11ea-96f6-69a287d9a96d.png)

![image](https://user-images.githubusercontent.com/61318135/80960380-5be72d80-8e26-11ea-8b78-ce41b82c4a06.png)

**Comment by winterflame** [comment]
functional bug
