### ISSUE TITLE
Broken image in Settings - Linked account page

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#267]
Steps:-
1. Enter the URL : https://www.topcoder.com/
2. Click on right side of profile icon
3. Click on Settings link.
4. Goto Accounts tab >> Linked Account
5. View the accounts linked.

Actual Result : A broken image displayed for the account.
Expected Result : Image should display for the account

Browser - Chrome.OS - Windows

![image](https://user-images.githubusercontent.com/61318135/80967124-783d9700-8e33-11ea-9d7b-faa3716b229c.png)

![image](https://user-images.githubusercontent.com/61318135/80967107-71168900-8e33-11ea-87ea-83c247845ce0.png)

**Comment by winterflame** [comment]
UI bug

**Comment by ab668685** [comment]
Hi Winterflame,

These bugs are been closed will not be considered?

**Comment by winterflame** [comment]
Hi @ab668685 , can you tell which site did you linked in the above screenshot? I tried to reproduce but cannot:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/4590317/81272335-ee363e00-907f-11ea-8d44-5620124dae09.png">

**Comment by winterflame** [comment]
OK, let's accept it as a functional bug (but not in scope for the current challenge which is focusing on UX/Usability), thanks.

**Comment by ab668685** [comment]
Please dont consider as functional bug.Image not displayed.It can be considered as UX bug.Image is not displayed to user?

**Comment by winterflame** [comment]
It's essentially a functional bug - IMO the code should not allow adding invalid external links. You can try to add some valid links to see if you still have the same issue. Actually I don't have any external links by default.
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/4590317/81274955-93064a80-9083-11ea-937a-c80109c9abcf.png">

**Comment by ab668685** [comment]
Hi Winterflame,

I had not added any external link.By default this icon appear which I had mentioned in bug.If any video required I can share.please try with other users

**Comment by winterflame** [comment]
Can you try to find which site it is by using the developer tools? I just added an invalid site, but the image is not broken:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/4590317/81276148-360b9400-9085-11ea-85fc-9b2941f01778.png">

**Comment by ab668685** [comment]
Please find below

![image](https://user-images.githubusercontent.com/61318135/81276695-ffc41980-9070-11ea-989d-8cece365f161.png)
