### ISSUE TITLE
broken image link in challenge list User profile

### ISSUE THREAD

**Issue by Abhas1992** [topcoder-platform/qa-fun#273]
screen shots

![Screenshot (170)](https://user-images.githubusercontent.com/63012651/80971649-b68a8480-8e3a-11ea-9d7f-6958fb62bca1.png)

**Reproduction Steps:**

- Go to https://www.topcoder.com/members/Abhas1992
- click on bug hunt
- click on view change icon 

**Expected Result:**
the view should be changed grid to list view
**Actual Result:**
after clicking the grid change the user image is broken

Device/OS: Laptop | Windows 8.1

Browser Information:Chrome 81.0.4044.129 | FF 75.0

**Comment by winterflame** [comment]
UI bug
