### ISSUE TITLE
profile details part is hidden under footer

### ISSUE THREAD

**Issue by Abhas1992** [topcoder-platform/qa-fun#274]
screen shots

![Screenshot (171)](https://user-images.githubusercontent.com/63012651/80971493-7fb46e80-8e3a-11ea-8d55-4102337484c8.png)

Reproduction Steps:

- Go to https://www.topcoder.com/members/Abhas1992
- scroll down
- observe the left side user details 

Expected Result:
the user details should be shown properly
Actual Result:
the user details part is hidden under footer

Device/OS: Laptop | Windows 8.1

Browser Information:Chrome 81.0.4044.129 | FF 75.0

**Comment by winterflame** [comment]
UI bug.
