### ISSUE TITLE
[Chrome] Extra text or unwanted text available in case studies page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#276]
Bug title - Extra text or unwanted text available in case studies page
Steps To Reproduce -

1. Go to https://www.topcoder.com/case-studies/harvard-tumor-hunt/
2. Scroll down and see the text at left side
3. Observe the extra text    as "L SEP"

Actual Result - Observe the extra text 

Expected Result - There should not be extra text or it must be meaningful
Device/OS/Browser Information: Laptop HP, Windows10 (64Bit) , ChromeVersion 81.0.4044.129

![Bug 5](https://user-images.githubusercontent.com/42939505/80983188-ef7e2580-8e49-11ea-98b4-6015d61d7ebe.png)

**Comment by winterflame** [comment]
cannot reproduce
<img width="539" alt="image" src="https://user-images.githubusercontent.com/4590317/81248796-c0d19c00-904f-11ea-965a-2f80b9afe259.png">
