### ISSUE TITLE
[Web-firefox] Log-in page popping up on hitting back button

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#28]
Reproduction Steps:
1.Open https://www.topcoder.com and Login as a valid user
2.Go to https://www.topcoder.com/challenges
3. Click Back button
Expected Result: Log-in page should not be displayed
Actual Result: Log-in page is popping up
Device/OS: Laptop | Windows 7
Browser Information:  Firefox 73.0.1 (64-bit)
[Log-in page popping up-1.zip](https://github.com/topcoder-platform/qa-fun/files/4277383/Log-in.page.popping.up-1.zip)

**Comment by winterflame** [comment]
cannot reproduce
