### ISSUE TITLE
Incorrect validation message " You have to pass reCAPTCHA to submit the form" for valid reCAPTCHA submission 

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#285]
Steps:-
1. Enter the URL : https://www.topcoder.com/
2. Click on Menu EnterPrise  >> ENTERPRISE CROWDTESTING
3. View the Page .
4. Donot enter any details .Click Submit.
5. Click on and Enter valid reCAPTCHA .
6. Click Submit

Actual Result : Incorrect validation message " You have to pass reCAPTCHA to submit the form"

Expected Result : Incorrect validation should not appear

Browser : Chrome ,Windows - OS

![image](https://user-images.githubusercontent.com/61318135/80990181-9adfa800-8e53-11ea-9e44-38e78a39adf9.png)

![image](https://user-images.githubusercontent.com/61318135/80990231-a501a680-8e53-11ea-8077-b3e268befc6a.png)

**Comment by winterflame** [comment]
This is not a bug, the user needs to select the checkbox before submitting the form.

**Comment by ab668685** [comment]
Hi Winterflame,
This is a bug.eventhough checkbox of recaptcha has been selected.Error message appears.

**Comment by winterflame** [comment]
Got it, thanks.
