### ISSUE TITLE
Tabular format header is missing for one column

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#288]
1) Go to https://www.topcoder.com/ 
2) Scroll down to bottom of the page
3) Observe below "QUESTIONS? CONTACT US"

Expected Result:
Next to COMPANY column header should be present.

Actual Result:
After COMPANY column header is missing 

Screenshot:
![3](https://user-images.githubusercontent.com/51490878/80991396-99af7a80-8e55-11ea-9f0a-0ea448b20468.png)

Device/OS/Browser Information:
Windows 10
Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by coderkid19** [comment]
![BrowserInfo_Chrome_81 0 4044 113](https://user-images.githubusercontent.com/51490878/80991474-bc419380-8e55-11ea-83be-cbe65367aece.png)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/80991477-be0b5700-8e55-11ea-8391-1ce59cbadfb8.png)

**Comment by winterflame** [comment]
duplicate
