### ISSUE TITLE
404 HTTP Error while loading My Profile Page 

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/qa-fun#295]
**Steps to Reproduce:**
1. Log in to the Topcoder application
2. On the right top corner, select on the logged in user name then a drop down menu comes, in that menu select "My Profile"

**Expected Result:** 

My Profile page should get opened 

**Actual Result:** 

404 HTTP Error page is coming. Please find the attachment for details.
[404 error on selecting my profile.docx](https://github.com/topcoder-platform/qa-fun/files/4576857/404.error.on.selecting.my.profile.docx)

**Device/OS/Browser Information:**
Windows 10/ Chrome browser in incognito mode

**Comment by winterflame** [comment]
1) Cannot reproduce, maybe the server was down.
2) Please just attach the screenshot in the bug report description. No need to attach a file for the whole bug report.

**Comment by ajithck333** [comment]
@winterflame Issue not resolved. Still able to reproduce. Fie contains screenshot only not bug report.

**Comment by winterflame** [comment]
Hi @ajithck333 , did you use email address to login, right? I can see your topcoder handle AjithKrishnan , so your profile page is: https://www.topcoder.com/members/AjithKrishnan
