### ISSUE TITLE
usability issue - no quick link to move to top

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/qa-fun#296]
After scrolling down to bottom of the website, user has to again scroll the entire way up to get to the top. There should be some quick link similar to the one highlighted in the below image. On clicking on which will automatically move to the top .

**Steps to Reproduce:** 
Login to the https://www.topcoder.com/ and then scroll down to bottom of the page

**Expected Result:**
There should be some quick link on the right hand side to move quickly to the top of the page 

**Actual Result:**

No quick link to move to the top of the page. User has to scroll manually 

[usability-no quick link to move to top.docx](https://github.com/topcoder-platform/qa-fun/files/4576956/usability-no.quick.link.to.move.to.top.docx)

**Device/OS/Browser Information:**

Windows 10 / Chrome

**Comment by winterflame** [comment]
@ajithck333 Can you update the screenshots properly (no need to use another docx file) in the bug description section?

**Comment by ajithck333** [comment]
@winterflame All screenshots are in the attached file "usability-no quick link to move to top.docx" If you are not able to open the file, please let me know. I will attach it again

**Comment by winterflame** [comment]
Hi @ajithck333 , please update all your reported bugs properly (just need to attach screenshots to the bug description area), thank you!

**Comment by ajithck333** [comment]
![image](https://user-images.githubusercontent.com/64805821/81427237-2f534e80-9163-11ea-9739-b63a5932226a.png)
