### ISSUE TITLE
[Web-Chrome] Background Logo Is Moving While Hovering Over Mouse On It

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#297]
1. Go To https://www.topcoder.com/

2. Login With Valid Credential

3. Hover Over Mouse On Background Logo Then See & Observe.

4. Expected Result:- Background Logo Should Not Move While Hovering Over Mouse On It.

5. Actual Result:- Background Logo Is Moving While Hovering Over Mouse On It.

6. Screencast:-
[Logo.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/4577242/Logo.mp4.zip)

7. Device:- Laptop

8. OS Version:-
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4577250/Mac.Version.png.zip)

9. Browser Information:
[Chrome Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4577255/Chrome.Version.png.zip)

**Comment by winterflame** [comment]
1) It's an visual effect by design.
2) Please avoid using *.zip for the screenshots/screencast - for the screenshots, just attach as an image, and give the direct link for screencast.
