### ISSUE TITLE
[Web-Chrome] Key Board Nav Is Automatically Selecting While ClickIng On Read Page

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#299]
1. Go to https://www.topcoder.com/

2. Login with valid credential

3. Scroll down mouse to right side bottom corner & click on Accessibility menu.

4. Click on Read Page then observe.

5. Expected Result:- Key Board Nav should not be selected automatically while clicking on Read Page

6. Actual Result:- Key Board Nav is selected while clicking on Read Page

7. Screencast & Screenshot:- 
[Keyboard Nav Is.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/4577523/Keyboard.Nav.Is.mp4.zip)

<img width="353" alt="image" src="https://user-images.githubusercontent.com/4590317/81392818-cc0cf080-9151-11ea-9aef-3967e3193229.png">

8. Device:- Laptop

9. OS Version: Mac OS
10. Browser Information: Google Chrome

**Comment by winterflame** [comment]
@devsreekrishna Do not capitalize the first character for all words in a sentence.
