### ISSUE TITLE
[Web-Firefox] Difference In Prize Amount

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#3]
1. Go To https://www.topcoder.com/challenges?bucket=reviewOpportunities

2. Login With Valid Uset

3. Click On Open For Review

4. Select Find & Replace For Key Word Search

5. See Screencast & Observe

[Difference In Amount.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/4275852/Difference.In.Amount.mp4.zip)

6. Expected Result: Both Prize Amount Should Be Same.

7. Actual Result: Both Prize Amount Is Different.

8. Device: Laptop

9. Operating System: MacOs 10.13.6
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4275860/Mac.Version.png.zip)

10. Browser:
[Firefox Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4275864/Firefox.Version.png.zip)

**Comment by winterflame** [comment]
One is the prize, the other is the review payment.
