### ISSUE TITLE
When you close and reopen the challenges page the toggle button's previous state is retained

### ISSUE THREAD

**Issue by Akhila-C-R** [topcoder-platform/qa-fun#30]
Steps to Reproduce:
1. Go to https://www.topcoder.com/challenges
2. Select any of the toggle button options- here  I have selected 'design' and 'development'
3. Close the tab and open it again

Expected Result:
The options are retained.

Actual Result:
Usually, such filter/toggle options should not be retained.

Screenshots or screencast:
[bug 2.zip](https://github.com/topcoder-platform/qa-fun/files/4277571/bug.2.zip)

Device/OS/Browser Information:
OS: Windows 8.1
Browser: Google Chrome version: 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
This is as designed.
