### ISSUE TITLE
[Chrome] Chip text is showing above the filter dialog and hiding data on filter dialog

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#307]
Bug title - Chip text is showing above the filter dialog when filter dialog is opened it hides the data

Steps To Reproduce -

1. Go to https://www.topcoder.com/?s=New
2. Now click on filter icon
3. Observe the chip text hide data on filter dialog

Actual Result - Chip text hide data on filter dialog

Expected Result - It should not hide the dialog data, it must be behind the dialog

Device/OS/Browser Information: Laptop HP, Windows10 (64Bit) , ChromeVersion 81.0.4044.129

![Bug 8](https://user-images.githubusercontent.com/42939505/81036051-36583380-8ebb-11ea-95a5-7629f41361bf.png)

**Comment by winterflame** [comment]
UI bug

**Comment by rajanmourya** [comment]
it is accepted or not?

**Comment by winterflame** [comment]
No, this challenge is focusing on UX/Usability bugs.
