### ISSUE TITLE
Submission page arrow mark is not shown properly

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#31]
Steps to Reproduce:

Go to https://www.topcoder.com/challenges
Open one registered challange and go to Submission page
Observe the arrow next to Username, Submission Date, Initial/Final score.

Expected Result:
Arrow should be displayed properly in Submission page

Actual Result:
Arrow not shown properly in Chrome

Screenshots or screencast:

Device/OS/Browser Information:
Windows 10,
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by coderkid19** [comment]
Same happens for Registrant page as well

**Comment by coderkid19** [comment]
![issue3](https://user-images.githubusercontent.com/51490878/75803036-bff86180-5da3-11ea-8496-7bfc07ec0891.png)
![BrowserInfo_Chrome_ 80 0 3987 116](https://user-images.githubusercontent.com/51490878/75803055-c555ac00-5da3-11ea-9033-5d987cfc5237.png)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/75803056-c555ac00-5da3-11ea-8b10-07013fb22d19.png)

**Comment by winterflame** [comment]
Unable to reproduce.
