### ISSUE TITLE
[Chrome] When pressing back button from PRESS & MEDIA REQUESTS page, the design is disordered, page is not properly designed

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#319]
Bug title - When going back from PRESS & MEDIA REQUESTS page, the design of page is not visible properly

Steps To Reproduce -

1. Go to https://www.topcoder.com/press-media-requests/
2. Now press the back button of the browser and observe
3. Observe the page design, it is not proper

Actual Result - Desing is distorted when going back through back button

Expected Result - Design should properly visible because of this user experience may affect
Device/OS/Browser Information: Laptop HP, Windows10 (64Bit) , ChromeVersion 81.0.4044.129

![Bug 13](https://user-images.githubusercontent.com/42939505/81040507-20516f80-8ec9-11ea-9f68-25a4047add7d.png)

**Comment by winterflame** [comment]
cannot reproduce
