### ISSUE TITLE
[Chrome] Show Deadlines/Hide Deadlines text is touching with Arrow mark 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#32]
Steps to Reproduce:

Go to https://www.topcoder.com/challenges
Open one challenge
Click on Show Deadlines on the right side.
Also, After it expends click on  Hide Deadlines
Observe the arrow 

Expected Result:
Show Deadlines/Hide Deadlines text should not touch with Arrow mark 

Actual Result:
Show Deadlines/Hide Deadlines text is touching with Arrow mark 

Screenshots or screencast:

Device/OS/Browser Information:
Windows 10,
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by coderkid19** [comment]
![Issue4](https://user-images.githubusercontent.com/51490878/75803222-1b2a5400-5da4-11ea-9b8a-16c18bb0cf7f.JPG)
![BrowserInfo_Chrome_ 80 0 3987 116](https://user-images.githubusercontent.com/51490878/75803230-1e254480-5da4-11ea-90d5-72f0559e8bfa.png)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/75803231-1ebddb00-5da4-11ea-82c3-afc8e834a58f.png)

**Comment by winterflame** [comment]
Not a functional bug.
