### ISSUE TITLE
Button height is low under the Banner

### ISSUE THREAD

**Issue by mukeshkishore** [topcoder-platform/qa-fun#323]
Steps:

1) Go to https://www.topcoder.com/case-studies/honeywell/
2) Under the banner "Connected Buildings"
3) Two button "APPS & WEBSITES" and "CROWDTESTING & QA".

Actual result: Both buttons height is low.
Expect result: Buttons height should be little bit increase.

Device: Dell
OS: Windows 10
Browser : Google Chrome
Version 81.0.4044.129 (Official Build) (64-bit)

![Uploading honeywell.png…]()
two button "APPS & WEBSITES" and "CROWDTESTING & QA".

**Comment by winterflame** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/4590317/81363561-34d67780-9116-11ea-8999-92eacddb14ae.png">
