### ISSUE TITLE
[Chrome] When hovering over text button is showing only on some part of text not all the text in the case study page

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#325]
Bug title - When hovering over text button is showing only on some part of text not all the text in the case study page

Steps To Reproduce -

1. Go to https://www.topcoder.com/case-study-types/apps-websites/
2. Scroll down and click on list view icon
3. Now hover over the view case study text observe button will appear only on the "view case" text not on "study"

Actual Result - Button is appearing only on the view case text not complete text

Expected Result - Button must appear on complete text
Device/OS/Browser Information: Laptop HP, Windows10 (64Bit) , ChromeVersion 81.0.4044.129

![Bug 18](https://user-images.githubusercontent.com/42939505/81043199-73c6bc00-8ecf-11ea-83f3-fabe5fc2f5fe.png)

**Comment by winterflame** [comment]
UI bug
