### ISSUE TITLE
font difference in profile settings

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/qa-fun#327]
**Steps to Reproduce:**

1.	Log in to https://www.topcoder.com/
2.	Select logged in user settings 
3.	Font highlighted in red in the attachment is different 

**Expected Result:**

Font should be unique 

**Actual Result:**

Font style not applied 

[font difference in profile settings.docx](https://github.com/topcoder-platform/qa-fun/files/4579363/font.difference.in.profile.settings.docx)

**Device/OS/Browser Information:**

Windows 10/ Chrome

**Comment by winterflame** [comment]
@ajithck333 Can you update the screenshots properly (no need to use another docx file) in the bug description section and in the circle the issues in the screenshots?

**Comment by ajithck333** [comment]
@winterflame all screenshots are in the attached file "font difference in profile settings.docx". If you are not able to open the file please let me know I will attach it again
"

**Comment by ajithck333** [comment]
![image](https://user-images.githubusercontent.com/64805821/81427548-9e30a780-9163-11ea-8fdb-4365e893f7a8.png)
