### ISSUE TITLE
[Web-Firefox] There Is A Straight Line In Between

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#330]
1. Go To https://www.topcoder.com/

2. Login As Valid Credentials

3. Scroll Down Mouse Below View Enterprise Offerings Then Observe.

4. See Screenshot.

5. Expected Result:- There Should Be No Straight Line In Between

6. Actual Result:- There Is A Straight Line In Between

7. Screenshot:- 
[There Is A Line.png.zip](https://github.com/topcoder-platform/qa-fun/files/4579415/There.Is.A.Line.png.zip)

8. Device:- Laptop

9. OS Version:-
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4579423/Mac.Version.png.zip)

10. Browser Information:-
[Firefox Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4579426/Firefox.Version.png.zip)

**Comment by winterflame** [comment]
As designed.
