### ISSUE TITLE
date picker is hiding behind the banner in profile settings

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/qa-fun#331]
**Steps to Reproduce:**

1.	Log in to https://www.topcoder.com/
2.	Select logged in user settings
3.	Select education from the left menu 
4.	Date picker is hiding behind the banner 

**Expected Result:** 

Date picker should be fully visible and should be able to select date 

**Actual Result:** 

Date picker is not visible and not able to select date 

[date picker hiding behind the banner in profile settings.docx](https://github.com/topcoder-platform/qa-fun/files/4579428/date.picker.hiding.behind.the.banner.in.profile.settings.docx)

**Device/OS/Browser Information:**

Windows 10/ Chrome

**Comment by winterflame** [comment]
@ajithck333 Can you update the screenshots properly (no need to use another docx file) in the bug description section?

**Comment by ajithck333** [comment]
@winterflame All screenshots are in the attached file "date picker hiding behind the banner in profile settings.docx" If you are not able to open the file please let me know. I will attach it again.

**Comment by ajithck333** [comment]
![image](https://user-images.githubusercontent.com/64805821/81427462-8527f680-9163-11ea-8c61-80f389ebedfc.png)

**Comment by winterflame** [comment]
UI bug
