### ISSUE TITLE
[Web-Firefox] Image Some Part Is Cutting

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#336]
1. Go To https://www.topcoder.com

2. Scroll Down Mouse Below To Bottom > Select Public Sector Then Observe.

3. See Screenshot

4. Expected Result:- Image Part Should Not Cut, It Should Shown Fully.

5. Actual Result:- Image Some Part Is Cutting

6. Screenshot:-
[Image Is Cutting.png.zip](https://github.com/topcoder-platform/qa-fun/files/4579599/Image.Is.Cutting.png.zip)

7. Device:- Laptop

8. OS Version:-
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4579605/Mac.Version.png.zip)

9. Browser Information:-
[Firefox Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4579610/Firefox.Version.png.zip)

**Comment by winterflame** [comment]
not a bug
