### ISSUE TITLE
[UX][Web-Firefox] App Contact page - Phone number field is showing error message on Valid phone number.

### ISSUE THREAD

**Issue by Nefeeza** [topcoder-platform/qa-fun#338]
Steps to Reproduce:
1, Go to URL https://www.topcoder.com/ 
2, Go to "Solutions" tab --> Apps tab. Click on "Start your app" button. App contact page is displayed.
3, Tap Phone number field, enter valid number "(732) 286-6000".
4, Tap next field "Tell us about your app". observe.

Expected Result:
Phone Number field should not display error message on valid number.
Phone Number field should accept ( ) - these symbols. Since most of the other websites are accepting these kind of number format.

Actual Result:
Phone Number field is displaying error message on valid number.

Screenshots:
![AppContact_ValidPhoneNumber](https://user-images.githubusercontent.com/61901295/81047799-cb1d5a00-8ed8-11ea-993c-13e2b6508c30.png)

Device/OS/Browser Information:
Device: HP Laptop
OS: Windows 10
![Browser](https://user-images.githubusercontent.com/61901295/81047830-dc666680-8ed8-11ea-8ee8-80310dec9732.png)

**Comment by winterflame** [comment]
similar to #334
