### ISSUE TITLE
There is no email client implemented for 'support@topcoder.com' on 'Privacy Policy' page

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/qa-fun#346]
Bug Title: There is no email client implemented for 'support@topcoder.com' on 'Privacy Policy' page

Steps to Reproduce:
1. Go to https://www.topcoder.com/
2. Scroll down to the end of the page and click on 'Privacy Policy'.
3. Scroll down on same page and click on any of the highlighted 'support@topcoder.com' link.
4. Observe a window appears for split second and disappears.
5. No email client opens to send mail to 'support@topcoder.com'.

Expected Result:
There should an email client available by default when user clicks on 'support@topcoder.com'.

Actual Result:
No email client opens when user clicks on 'support@topcoder.com'.

Screenshots or screencast:
![image](https://user-images.githubusercontent.com/12671119/81061871-ba79dd80-8ef2-11ea-8944-92163a071258.png)

[No_Email_Client.zip](https://github.com/topcoder-platform/qa-fun/files/4580431/No_Email_Client.zip)

Device/OS/Browser Information:
Platform - Windows 10
operating system 
Microsoft Windows 10 Enterprise Version 10.0.17763 Build 17763
Browser - Chrome - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by winterflame** [comment]
It depends on whether the user has installed any email clients.

**Comment by Manonita** [comment]
I have Outlook 2016 installed on my laptop but it wasn't detected.

**Comment by winterflame** [comment]
Thanks for letting me know. But it's just a "mailto" link, seems it depends on the settings on the user side: https://www.msoutlook.info/question/mailto-links-do-not-open-outlook

**Comment by Manonita** [comment]
Yes maybe.
Please suggest developer to check the network response once.
Also please observe a window appearing for split second on the screen when user clicks on email link.
PFB network response.

![image](https://user-images.githubusercontent.com/12671119/81405077-9a495900-9154-11ea-9a6b-e2faf1de6f9d.png)


![image](https://user-images.githubusercontent.com/12671119/81405106-a9300b80-9154-11ea-8b31-393ae164368a.png)


Thanks!
