### ISSUE TITLE
email validation is not happening in contact us form

### ISSUE THREAD

**Issue by sridevinagaraj** [topcoder-platform/qa-fun#347]
Bug Title:  email validation is not happening in contact us form
Steps to Reproduce: go to https://www.topcoder.com/contact-us/
Expected Result: email validation should happen
Actual Result: email validation is not happening in contact us form
Screenshots or screencast: ![I1](https://user-images.githubusercontent.com/25819254/81062283-50ae0380-8ef3-11ea-90d8-850c5d4230a0.PNG)
Device/OS/Browser Information: Windows 7,chrome
![I2](https://user-images.githubusercontent.com/25819254/81062474-a682ab80-8ef3-11ea-9b23-42209d49544a.PNG)

**Comment by winterflame** [comment]
Steps to reproduce are incomplete.
