### ISSUE TITLE
sponsorship-info page is not loading for 5 min.

### ISSUE THREAD

**Issue by sridevinagaraj** [topcoder-platform/qa-fun#349]
Bug Title:  sponsorship-info page is not loading for 5 min.
Steps to Reproduce: go to https://www.topcoder.com/sponsorship-info
Expected Result: page should load
Actual Result: Not loading
Screenshots or screencast: 
![I3](https://user-images.githubusercontent.com/25819254/81062834-56f0af80-8ef4-11ea-857e-6029394ccf55.PNG)

Device/OS/Browser Information: Windows 7, Chrome

**Comment by winterflame** [comment]
cannot reproduce
