### ISSUE TITLE
 email validation is not happening

### ISSUE THREAD

**Issue by sridevinagaraj** [topcoder-platform/qa-fun#350]
Bug Title: email validation is not happening in contact us form
Steps to Reproduce: go to https://www.topcoder.com/solutions/qa-testing/qa-testing-contact/
Expected Result: email validation should happen
Actual Result: email validation is not happening in contact us form
Screenshots or screencast:
![I4](https://user-images.githubusercontent.com/25819254/81063362-43921400-8ef5-11ea-825e-5ce49ba69518.PNG)

**Comment by winterflame** [comment]
Steps to reproduce are incomplete.
