### ISSUE TITLE
Only 'VIEW CASE' is highlighted when user brings cursor to the section of ' VIEW CASE STUDY' button

### ISSUE THREAD

**Issue by Manonita** [topcoder-platform/qa-fun#355]
Bug Title: Only 'VIEW CASE' is highlighted when user brings cursor to the section of ' VIEW CASE STUDY' button

Steps to Reproduce:
1. Go to https://www.topcoder.com/
2. Click on 'Case Studies' from top menu.
3. Following page opens -> https://www.topcoder.com/case-study-search/
4. Select 'ALL' as filter for ' VIEW CASE STUDIES BY: '
5. Scroll down and click on 'USA DIVING APP'.
6. A new page will open -> https://www.topcoder.com/case-studies/usa-diving/
7. Scroll down and notice there is a link -> APPS & WEBSITES
8. User clicks on 'APPS & WEBSITES'
9. A new page opens -> https://www.topcoder.com/case-study-types/apps-websites/
10. Scroll down and select the middle option which is - **display as list.**
11. Notice the ' VIEW CASE STUDY' button.
12. Only 'VIEW CASE' is highlighted when user brings cursor to the section of ' VIEW CASE STUDY' button

Expected Result:
User should be allowed to enter limited text in the search field.

Actual Result:
User is allowed to enter unlimited text in the search field.

Screenshots or screencast:
![image](https://user-images.githubusercontent.com/12671119/81069663-cfa93900-8eff-11ea-867c-338bd4e8108f.png)

![image](https://user-images.githubusercontent.com/12671119/81069735-eb144400-8eff-11ea-8a23-e11e75b4da75.png)

![image](https://user-images.githubusercontent.com/12671119/81069936-36c6ed80-8f00-11ea-9ede-353109dd1a25.png)

![image](https://user-images.githubusercontent.com/12671119/81070067-5fe77e00-8f00-11ea-9625-fe6cb6a8e3ef.png)

Device/OS/Browser Information:
Platform - Windows 10
operating system 
Microsoft Windows 10 Enterprise Version 10.0.17763 Build 17763
Browser - Chrome - Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by winterflame** [comment]
duplicated
