### ISSUE TITLE
unable to update country in user settings 

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/qa-fun#358]
**Steps to Reproduce:**

1.	Log in to https://www.topcoder.com/ application 
2.	Go to settings screen of logged in user 
3.	In the basic info, update country and click on save changes, page says “Success”.
4.	Refresh the page and still county is showing old value 

**Expected Result:**

Country should get updated with new value.

**Actual Result:** 

After update county is showing old value even if save displayed success

[unable to update county in user settings.docx](https://github.com/topcoder-platform/qa-fun/files/4581365/unable.to.update.county.in.user.settings.docx)

**Device/OS/Browser Information:** 

Windows 10 / Chrome

**Comment by winterflame** [comment]
@ajithck333 Can you update the screenshots properly (no need to use another docx file) in the bug description section?

**Comment by ajithck333** [comment]
@winterflame All screenshots are in the attached file "unable to update county in user settings.docx" If you are not able to open the file please let me know I will attach it again

**Comment by ajithck333** [comment]
![image](https://user-images.githubusercontent.com/64805821/81427348-5f025680-9163-11ea-9e15-258f4221bc6e.png)
![image](https://user-images.githubusercontent.com/64805821/81427368-63c70a80-9163-11ea-88d4-e159cdaf8190.png)
![image](https://user-images.githubusercontent.com/64805821/81427382-69bceb80-9163-11ea-9605-54e5c7d9f750.png)
![image](https://user-images.githubusercontent.com/64805821/81427399-72152680-9163-11ea-8166-7634b2e0ff9e.png)
