### ISSUE TITLE
"404 HTTP Error" on login

### ISSUE THREAD

**Issue by AshrutArya** [topcoder-platform/qa-fun#359]
**Bug Title:** "404 HTTP Error" on login

**Steps to Reproduce:** 
1. Login to topcoder using google
2. Go to "My Profile"

**Expected Result:** "My profile - Dashboard or Profile page"

**Actual Result:** "404 HTTP Error"

**Screenshots:**

1. Before Login:
![Screenshot (229)](https://user-images.githubusercontent.com/24873510/81181887-b5885d00-8fca-11ea-8f21-0eaf0d0c20c3.png)

2. Choose Google on login screen:
![Screenshot (231)](https://user-images.githubusercontent.com/24873510/81181969-d486ef00-8fca-11ea-9357-2e37447e6d68.png)

3. Logged in account:
![Screenshot (232)](https://user-images.githubusercontent.com/24873510/81182009-e2d50b00-8fca-11ea-87bd-0ba8ac862baf.png)

4. Choose "My Profile" in dropdown:
![Screenshot (233)](https://user-images.githubusercontent.com/24873510/81182061-f7190800-8fca-11ea-9978-85eaa3e8608d.png)

5. Error Page
![Screenshot (234)](https://user-images.githubusercontent.com/24873510/81182096-00a27000-8fcb-11ea-9d43-dc064f2bd61a.png)

**Device/OS/Browser Information:** 
Device: HP Spectre Notebook, Intel(R) Core(TM) i7-6500 CPU, 8GB RAM, 64 Bit OS
OS: Windows 10 Home, version 1909 Build: 18363.778 
Browser: Google Chrome, Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by winterflame** [comment]
This is a functional bug.
