### ISSUE TITLE
"Past Challenges" does not show Unregistered Challenges

### ISSUE THREAD

**Issue by AshrutArya** [topcoder-platform/qa-fun#363]
**Bug Title:** "Past Challenges" does not show Unregistered Challenges

**Steps to Reproduce:** 
1. Go to your Dashboard
2. Select "Past Challenges"

Alternatively - Add Registering & then Unregistering in a challenge to test the functionality.

**Expected Result:** All the challenges in the past, including challenges which user unregistered after a bit.

**Actual Result:** Only the challenges which the user did not unregister from.

**Screenshots:**
1. Dashboard - My challenges:
![Screenshot (252)](https://user-images.githubusercontent.com/24873510/81189934-d2c22900-8fd4-11ea-8a62-69d27aef9719.png)
![Screenshot (253)](https://user-images.githubusercontent.com/24873510/81189878-bd4cff00-8fd4-11ea-9664-77107aac577c.png)

2. Past Challenges (Missing Unregistered challenges)
![Screenshot (254)](https://user-images.githubusercontent.com/24873510/81189999-e4a3cc00-8fd4-11ea-8692-a77f9174164c.png)

**Device/OS/Browser Information:** 
Device: HP Spectre Notebook, Intel(R) Core(TM) i7-6500 CPU, 8GB RAM, 64 Bit OS
OS: Windows 10 Home, version 1909 Build: 18363.778 
Browser: Google Chrome, Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by winterflame** [comment]
not necessary
