### ISSUE TITLE
The "submit" button on the dashboard page leads to a blank screen

### ISSUE THREAD

**Issue by tralph3** [topcoder-platform/qa-fun#365]
**Steps to reproduce:**
* Go to the "My Dashboard" section.
* On the "My Active Challenges" section, choose any project you want and click "Submit".

**Expected Result:**
* The submit window appears and you can submit your work for that challenge.

**Actual Result:**
* A blank page appears.

**Screenshot:**
[Picture](https://i.imgur.com/0jvjDOt.png)

**Information:**
* Browser: Firefox 76.0 (64-bit)
* OS: Windows 7 Ultimate 64-bit
* Device: Thinkpad T430

**Further Notes:**
* Reloading the page fixes the issue.

**Comment by winterflame** [comment]
functional bug
