### ISSUE TITLE
[window-10] In Dashboard in MY EARNINGS AND STATS Continuously loading not providing any result to user. 

### ISSUE THREAD

**Issue by Marvel999** [topcoder-platform/qa-fun#38]
### Step to reproduce:
1. Go to the link:- https://www.topcoder.com/challenges/30117155
2. Click on topcoder icon
3. Go to the desboard.
4.On desboard there is MY EARNINGS AND STATS section it does not providing any result

### Expected result:
Should provide any result after loading.

### Actual result:
Does not provide any result after loading and is continuously loading.

### Screenshots or screencast:
https://drive.google.com/drive/folders/1BKhRXi2IK9qWlkGA_Wr3z3j0zeJmoPH1?usp=sharing

####  Device/OS/Browser Information:
Laptop [hp 15-da0352tu]/Window-10/Chrome (64-bit)

**Comment by winterflame** [comment]
It's a bug but not in scope for this challenge.
