### ISSUE TITLE
Footer broken line or context missing

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#385]
Steps:-

1. Enter the URL topcoder.com
2. Goto footer.
3. View the Contact US

Actual Result : Context missing as shown in below image or broken line.

Expected Result : Context should be there or line should be appended.Should be similar like other lines.

Browser : Chrome ,OS - Windows

![image](https://user-images.githubusercontent.com/61318135/81306366-02d4ff00-909d-11ea-9a3b-6b120af5e36d.png)

![image](https://user-images.githubusercontent.com/61318135/81307658-893e1080-909e-11ea-9d07-3f7aecbeea54.png)

**Comment by winterflame** [comment]
duplicate

**Comment by ab668685** [comment]
Hi WinterFlame,
This bug is a duplicate of which bug ?I had mentioned 2 bugs - 1. Context missing and 2 . line broken

**Comment by winterflame** [comment]
It was reported in previous bug hunt challenge.

**Comment by ab668685** [comment]
Thanks for the confirmation.
