### ISSUE TITLE
Images are not proper aligned ;padding issue

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#386]
Steps:-

1. Enter the URL : topcoder.com
2. View the below images of our customer top stories.

Actual Result : Company images are not aligned properly.
Expected Result : Padding issue should be fixed 

Browser : Chrome : Windows 10: OS

![image](https://user-images.githubusercontent.com/61318135/81308317-416bb900-909f-11ea-9384-886345733650.png)

![image](https://user-images.githubusercontent.com/61318135/81308401-5a746a00-909f-11ea-975d-c38d79997aff.png)

**Comment by winterflame** [comment]
duplicate with #287

**Comment by ab668685** [comment]
I hope most of the bugs will be validated based on quality of UX bugs and not based on number of blank space bugs.
