### ISSUE TITLE
[Window-10] In Challenge Fourm Topcoder icon is not Functioning to go desboard or Home page of topcoder.

### ISSUE THREAD

**Issue by Marvel999** [topcoder-platform/qa-fun#39]
### Step to reproduce:-
1. Go to the link:-https://www.topcoder.com/challenges?tab=details
2. Register on ANY Challenges and Go into the Challeng fourm Section.
3. Click on Topcoder icon provided on top.

### Expected result:
Icon is non clickable not going into Desboard or not going into home page.

### Actual result:
Should be clickable and going into Desboard or going into home page.

### Screenshots or screencast:
https://drive.google.com/drive/folders/1lzpSoXUDcQPawyFkkEbuDFSzbrMpGnWR?usp=sharing

####  Device/OS/Browser Information:
Laptop [hp 15-da0352tu]/Window-10/Chrome (64-bit)

**Comment by winterflame** [comment]
Not in scope
