### ISSUE TITLE
Article from username missing

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#391]
Steps:-
1. Enter the URL : topcoder.com
2. Click on Tracks >> Competitive Programming.
3. View the articles and written by

Actual Result : Articles from username missing
Expected Result : Articles from username should diaplay

Windows 10 -OS ,Browser : Chrome

![image](https://user-images.githubusercontent.com/61318135/81316682-84cb2500-90a9-11ea-9fa8-aeadeb138c1b.png)

![image](https://user-images.githubusercontent.com/61318135/81316732-93194100-90a9-11ea-9df9-6f7bd60165c5.png)

**Comment by winterflame** [comment]
Not a bug, this is a topcoder handle.

**Comment by ab668685** [comment]
This is a bug.That is not a handle.Can you please provide that handle name.I felt its missing from the page.If its a name it should be a name not starting with []

**Comment by winterflame** [comment]
See https://www.topcoder.com/members/[[rng_58]]

**Comment by ab668685** [comment]
ok got it.Thanks for the confirmation
