### ISSUE TITLE
404 HTTP Error while loading My Profile Page - creating again since issue is not resolved and not able t reopen #295

### ISSUE THREAD

**Issue by ajithck333** [topcoder-platform/qa-fun#395]
Steps to Reproduce:

Log in to the Topcoder application
On the right top corner, select on the logged in user name then a drop down menu comes, in that menu select "My Profile"
Expected Result:

My Profile page should get opened

Actual Result:

404 HTTP Error page is coming. Please find the attachment for details.
404 error on selecting my profile.docx

Device/OS/Browser Information:
Windows 10/ Chrome browser in incognito mode
![404](https://user-images.githubusercontent.com/64805821/81395063-a5d45a00-912b-11ea-87dc-45c52a9c308a.JPG)

**Comment by winterflame** [comment]
See #295
