### ISSUE TITLE
Small letter instead of Capital letter for niche developers.

### ISSUE THREAD

**Issue by mukeshkishore** [topcoder-platform/qa-fun#396]
Steps:

1) Go to the link  topcoder.com/enterprise-offerings/.
2)Under the "TRANSFORM YOUR APPROACH TO DIGITAL WORK" 
3) Under the "On demand access to specialized skill".
4) Data Scientists, QA Testers, UI Designers, niche Developers & beyond.

Actual Result: "niche" is started with small letter.

Except Result: It should start with Capital letter "Niche Developers".

Device: Dell
OS: Windows 10
Browser : Google Chrome
Version 81.0.4044.138 (Official Build) (64-bit)
![niche (2)](https://user-images.githubusercontent.com/52736834/81397370-cceb5580-9144-11ea-93e1-70e8d369eff2.png)

**Comment by winterflame** [comment]
not an issue
