### ISSUE TITLE
My Profile button is throwing 404 error found

### ISSUE THREAD

**Issue by nishanth-nk** [topcoder-platform/qa-fun#398]
Steps to Reproduce: 
1. Go to https://www.topcoder.com/ 
2. Click on user name at the right corner and selet My Profile option
3. After movied to https://www.topcoder.com/members/nishanth.k62 , It is showing like "404 HTTP Error" The resource you are looking for does not exist in Topcoder community App :(.

Expected Result: My Profile option should show the user profile page.

Actual Result: My Profile is showing "404 HTTP Error" The resource you are looking for does not exist in Topcoder community App :(.

![image](https://user-images.githubusercontent.com/37466460/81404026-9e4c8b00-9102-11ea-917c-e3b0545129e8.png)

![image](https://user-images.githubusercontent.com/37466460/81404049-a6a4c600-9102-11ea-9fec-7779cdb742de.png)

Device/OS/Browser Information: Desktop #AMD R3 pro 2200 G HP Pro A Seri/ Windows 10 Pro 64 Bit / Google Chrome Version 81.0.4044.138

**Comment by winterflame** [comment]
I can see your profile: https://www.topcoder.com/members/nishanth_nk , so the system considers the email username as your topcoder handle, right?

**Comment by winterflame** [comment]
dupe with #359
