### ISSUE TITLE
[Windows 10] "contact" redirecting to wrong page

### ISSUE THREAD

**Issue by lucosmo** [topcoder-platform/qa-fun#40]
Bug Title: "Contact" direct to wrong page

Steps to Reproduce:
1. go to: https://www.topcoder.com/challenges
2. On the right side of screen there is small container containing: 'all challenges', 'my challenges', 'open for registration' etc
3. Under container there are links 'about', 'contact', 'help' etc.
4. click on link 'contact'

Expected Result:
Directing to 'contact' page https://www.topcoder.com/community/contact

Actual Result:
Directing to https://www.topcoder.com/thrive/tracks?track=Topcoder/hc/en-us/articles/219069687-Contact-Support

Screenshots or screencast:
1. placement of 'contact' link
![topcoder1](https://user-images.githubusercontent.com/3357786/75776243-85fb7100-5d4b-11ea-9410-e149aaae9b37.png)
2. page linked to 'contact' link
![topcoder2](https://user-images.githubusercontent.com/3357786/75776239-8562da80-5d4b-11ea-80a8-bc5f360783a7.png)

Device/OS/Browser Information:
Dell lntel Core i5/ Windows 10/ Google Chrome Version 80.0.3987.122 64bit

**Comment by winterflame** [comment]
Duplicated with #34
