### ISSUE TITLE
'user img' not visible

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#403]
Steps:

1. Open https://www.topcoder.com/members/USERNAME
2. Open any random subtrack (for example "BUG_HUNT")
3. Click on this button (in image below)
![Screenshot from 2020-05-08 23-34-28](https://user-images.githubusercontent.com/32861951/81434955-a77e3c00-9184-11ea-8e35-8e7b4560332f.png)

Expected Result:
1. Cross button should be fully visible
2. User Image should be visible

Actual Result:
1. Cross button partially visible
2. Instead of user image, it shows "user img".

Screenshot:
![Screenshot from 2020-05-08 23-26-09](https://user-images.githubusercontent.com/32861951/81435157-ffb53e00-9184-11ea-8f96-ea43dffeff89.png)

Device/OS/Browser Information: i5 7 gen, Windows 10 , Firefox 75.0

**Comment by winterflame** [comment]
UI bug
