### ISSUE TITLE
My Communities: partially visible

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#404]
Steps:
1. Go to https://www.topcoder.com/my-dashboard
2. See My communites

Expected Result:
All details of each community should be visible

Actual result:
Doesnt show "Purse Cash" fully

![Screenshot from 2020-05-08 23-43-45](https://user-images.githubusercontent.com/32861951/81435921-3770b580-9186-11ea-80b5-4b7f3925f43c.png)

Device/OS/Browser Information: i5 7 gen, Windows 10, Firefox 75.0
Window width: 654 px

**Comment by winterflame** [comment]
Should be tested in normal window width.
