### ISSUE TITLE
Payments tab leads to old website design

### ISSUE THREAD

**Issue by ricardofachinello** [topcoder-platform/qa-fun#417]
**Steps to Reproduce:** 
1 - The user needs to have a valid account and to be logged in.
2 - Click on the "Payments" tab at the top of [topcoder.com/community/learn](topcoder.com/community/learn)

**Expected Result:** User is taken to the payments tab which follows the design language of the rest of the website.

**Actual Result:** User is taken to the payments tab which still uses the old 2015 design.

**OS/Browser Information:** Windows 10 - Build 18363.778 64-bit, Google Chrome  81.0.4044.129 64-bit.

![1](https://user-images.githubusercontent.com/26444633/81518282-f4444d00-9313-11ea-8785-a4a19540159c.png)
![2](https://user-images.githubusercontent.com/26444633/81518435-6c127780-9314-11ea-92d7-6602dcdf6785.png)

**Comment by winterflame** [comment]
dupe with #416
