### ISSUE TITLE
Clicking on the Topcoder logo on the Payments tab does not take to user to the website's index

### ISSUE THREAD

**Issue by ricardofachinello** [topcoder-platform/qa-fun#419]
**Steps to Reproduce:**
1 - The user needs to have a valid account and to be logged in.
2 - Click on the "Payments" tab at the top of [topcoder.com/community/learn](topcoder.com/community/learn)
3 - Click on the Topcoder logo at the top left corner. 

**Expected Result:** User is taken to the website's index.

**Actual Result:** Nothing happens.

**OS/Browser Information:** Windows 10 - Build 18363.778 64-bit, Google Chrome 81.0.4044.129 64-bit.

![1](https://user-images.githubusercontent.com/26444633/81518831-b34d3800-9315-11ea-8c43-10971f7fd3a5.png)
![2_mod](https://user-images.githubusercontent.com/26444633/81518978-09ba7680-9316-11ea-997e-613840eb28fd.png)

**Comment by winterflame** [comment]
#418
