### ISSUE TITLE
"Open for review" page loading time is more than 10 sec

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#42]
Steps to Reproduce :
1. Go to https://www.topcoder.com/challenges
2. Click on Open for review link found at right side panel
3. Observe the page loading time

Expected Result:
“Open for review” page loading time should be within 7 sec

Actual Result:
“Open for review” page loading time is more than 10 sec

Screenshots or screencast:
![image](https://user-images.githubusercontent.com/56633093/75773931-ddfa9d80-5d74-11ea-9a3c-24570c641865.png)

Device/OS/Browser Information:
<Detailed device: Lenovo Desktop, Operating System: Windows 10 Enterprise and Browser information: Google Chrome Version 80.0.3987.122 >

**Comment by winterflame** [comment]
Not a bug, it depends on network connection speed.
