### ISSUE TITLE
Title overlaps with paragraph 

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/qa-fun#428]
Steps to Reproduce:

1. Go to https://www.topcoder.com/ 
2. Click on Enterprise tab.
3. Click on Workforce Transformation tab.
4. Scroll down and observe "THE NEXT-GENERATION OF WORK" title.

Expected Result:
Title and paragraph should have some space in between.

Actual Result:
Title and paragraph overlap.

Screenshot:
![overlap](https://user-images.githubusercontent.com/48605524/81531462-144f2d00-9363-11ea-862d-5b242598e97d.jpg)

Device: Lenovo Ideapad 700
OS: Windows 10
Browser: Google Chrome
Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by winterflame** [comment]
cannot reproduce
