### ISSUE TITLE
Unaligned buttons

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/qa-fun#429]
Steps to Reproduce:

1. Go to https://www.topcoder.com/
2. Click on Public sector tab.
3. Scroll down and observe "LET'S GET STARTED" and "DOWNLOAD THE BOOK" buttons.

Expected Result:
Buttons should be aligned.

Actual Result:
Buttons aren't aligned.

Screenshot:
![alligned buttons](https://user-images.githubusercontent.com/48605524/81532342-83795100-9364-11ea-89cc-629ca9864ad6.jpg)

Device: Lenovo Ideapad 700
OS: Windows 10
Browser: Google Chrome
Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Cannot reproduce.
