### ISSUE TITLE
[TCO20-REGIONAL] [android] search does not work on people

### ISSUE THREAD

**Issue by dimkadimon** [topcoder-platform/qa-fun#441]
Bug Title: [android] search does not work on people

Steps:
1. Type in "Andrew Ng" in the search bar
2. Press search

Expected result:
Andrew Ng's deeplearning.ai course should come up where he is the instructor.

Actual result:
Other courses come up in the results list, which do not have Andrew Ng as instructor.

Screenshot:
![Screenshot_20200802-160933_Coursera](https://user-images.githubusercontent.com/5743594/89117150-c1f15880-d4da-11ea-8db8-f7116d970e0c.jpg)

**Comment by winterflame** [comment]
@dimkadimon Please attach a screenshot for this, thanks.
