### ISSUE TITLE
[TCO20-REGIONAL] [android-browser] help menu does not display recommended articles properly

### ISSUE THREAD

**Issue by dimkadimon** [topcoder-platform/qa-fun#444]
Bug Title: [android-browser] help menu does not display recommended articles properly

Steps:

1. Select some course on android app
2. Scroll down to the bottom and click "Learner Help Center". This will open the help center in browser.
3. Scroll down to Recommended Articles

Expected result:
The titles of recommended articles should be fully visible.

Actual result:
The titles of recommended articles are truncated.

Screenshot:
![Screenshot_20200802-161617_Chrome](https://user-images.githubusercontent.com/5743594/89117321-f7e30c80-d4db-11ea-99cb-f26d7aa631bc.jpg)

**Comment by winterflame** [comment]
This is not a bug. Also, we don't test on mobile browsers.
