### ISSUE TITLE
Challenges tags whole section not working as link but seem to link

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/qa-fun#45]
**Step to reproduce**
1. Go to the topcoder page and login with a valid user.
2. Observe tags of challenge like BH, Cd, MM, IG
3. Hove over the tags seem as link but only TCO section work as link

**Expected Result**
If whole section visible as link so it should be work

**Actual page** 
Whole tags section does not work as link while seeming as link

**Screenshot**
https://drive.google.com/open?id=1xmLCSy_50A0BuiweQDCUmzo-tnbxVzi3

**OS /Device info** 
Lenovo, Windows 10 

**Browser Info**
Firefox 72.0.2

**Comment by winterflame** [comment]
not a bug
