### ISSUE TITLE
[Web-Firefox] Inaccurate Registration and winners date

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#46]
Reproduction Steps:
1.Open https://www.topcoder.com and Login as a valid user
2.Go to https://www.topcoder.com/challenges
3. Click on Past challenges
4.Click any challenges

Expected Result: Correct registration date should be shown
Actual Result: Inaccurate registration date is shown { Date shown as registration date is past the winners date}
Device/OS: Laptop | Windows 7
Browser Information: Firefox73.0.1 (64-bit)
Screencast: [Wrong Registration date.zip](https://github.com/topcoder-platform/qa-fun/files/4282502/Wrong.Registration.date.zip)

**Comment by winterflame** [comment]
![image](https://user-images.githubusercontent.com/4590317/76051442-c6562b80-5fa5-11ea-80d5-5d0fec445a12.jpg)

**Comment by winterflame** [comment]
@Peppa-2016 Better to provide a screenshot too.
