### ISSUE TITLE
[TCO20-REGIONAL][Web-Chrome] On-top modal Background Let's the user to exit from the on-top modal page

### ISSUE THREAD

**Issue by trivia79** [topcoder-platform/qa-fun#467]
Repro Steps:
1. Go to https://www.coursera.org/
2. Click "Log In" or "Join for free"
3. Wait for the on-top modal sign-up page
4. Click on any transparent background
5. Observe how the modal does not affect
6. Click on the edge of the transparent background (like on the screenshot. Mouse cursor have to be on the edge most)
7. Notice how the on-top modal page disappeared

Actual Result:
The on-top modal page disappeared

Expected Result:
On-top modal page should not disappear. Or when clicking the background, on-top modal page can disappear wherever you click the cursor.

Device/Browser Name:
Asus (K401UB); 64-bit OS; x64-based processor /  Chrome Version 84.0.4147.105 (Official Build) (64-bit)

OS Version:
Windows 10 Home Single Language

![image](https://user-images.githubusercontent.com/38703430/89118582-42af5500-d4d9-11ea-9560-214c19382915.png)

**Comment by winterflame** [comment]
good catch!
