### ISSUE TITLE
[TCO20-REGIONAL][Web-Chrome] Selection of options from filters does not stay in place

### ISSUE THREAD

**Issue by trivia79** [topcoder-platform/qa-fun#470]
Repro Steps:
1. Go to https://www.coursera.org/
2. In the search box, type "excel" and press Enter key
3. Click Language filter
4. Click "Show All"
5. From the options, click "Bengali"
6. Observe what happened
7. Click "Tagalog" and observe also what will happen

Actual Result:
Selected options vanished from their positions and placed on first items.

Expected Result:
Selected options should stay in place. It's not the natural behavior for the user to find out that the selections has been placed before the first item.

Device/Browser Name:
Asus (K401UB); 64-bit OS; x64-based processor /  Chrome Version 84.0.4147.105 (Official Build) (64-bit)

OS Version:
Windows 10 Home Single Language

![image](https://user-images.githubusercontent.com/38703430/89118876-0c270980-d4dc-11ea-97fd-0877118f73bb.png)

![image](https://user-images.githubusercontent.com/38703430/89118881-1fd27000-d4dc-11ea-8173-870acaa92af2.png)

**Comment by winterflame** [comment]
This feature is as designed.
