### ISSUE TITLE
Search field level validation is not happened(i.e user is able to enter the special characters in " search challenge " section #47

### ISSUE THREAD

**Issue by JAMa1994** [topcoder-platform/qa-fun#48]
**Step to reproduce**

Go to the topcoder page and login with valid user.
Enter some special characters and "n" of values in search challenges section
Verify any error message is thrown in field or not

**Expected Result**
Search field level error message should be displayed

**Actual result**
Search field validation is not happened and user is able to enter the special characters ans " n" of numbers in search field

**Screenshot**
![image](https://user-images.githubusercontent.com/34433543/75801582-668f3300-5da1-11ea-81e4-ba2eeb44058e.png)

![image](https://user-images.githubusercontent.com/34433543/75801818-be2d9e80-5da1-11ea-8c74-f8cf3447e5dc.png)

**Device/OS/Browser Information:**
Windows 10 /  chrome 80.0

**Comment by winterflame** [comment]
Not a bug. The user is allowed to enter any characters to search. Also the search functionality is working as expected here - no records are shown for the entered keywords.
