### ISSUE TITLE
[TCO20-REGIONAL][Web-Chrome] "Enroll For Free" button appearance is not consistent

### ISSUE THREAD

**Issue by trivia79** [topcoder-platform/qa-fun#485]
Repro Steps:
1. Go to https://www.coursera.org/
2. In the search box, type "excel" and press Enter key
3. Click the first item "Excel Skills for Business" by "Macquarie University"
4. A new browser tab will open.
5. Click the second item "Everyday Excel, Part 1" by "University of Colorado Boulder"
6. A new browser tab will open.
7. Click the third item "Fundamentos de Excel para Negocios" by "Universidad Austral"
8. A new browser tab will open.
9. On each tab opened, scroll at the bottom of the page
10. Notice how each banner for each page have different "Enroll for free" button

Actual Result:
"Enroll for Free" button is not consistent throughout the course pages

Expected Result:
"Enroll for Free" button is must be consistent throughout the course pages

Device/Browser Name:
Asus (K401UB); 64-bit OS; x64-based processor /  Chrome Version 84.0.4147.105 (Official Build) (64-bit)

OS Version:
Windows 10 Home Single Language

![image](https://user-images.githubusercontent.com/38703430/89119927-780d7000-d4e4-11ea-99fd-6f33e2e02e70.png)

**Comment by winterflame** [comment]
not sure if it is intended, consider it as an enhancement.
