### ISSUE TITLE
[TCO20-REGIONAL][iOS] Course Screen Bigger Text

### ISSUE THREAD

**Issue by radoy** [topcoder-platform/qa-fun#489]
Steps to Reproduce:
	1. Set you iphone text to bigger
	2. Subscribe to a course then open that course
	3. Click a course

Actual Result:
	The tab text not shown correctly

Expected Result:
	The tab text should show all the tab text

Device/Browser Name:
    iPhone 7 

OS Version:
	13.6

![photo_2020-08-02 16 33 10](https://user-images.githubusercontent.com/907205/89120149-1fd36f80-d4de-11ea-873f-39a287388687.jpeg)

**Comment by winterflame** [comment]
It's valid, but it came after the submission phase ended. So we will not count it.
