### ISSUE TITLE
User is able to enter the special characters in filter sections 

### ISSUE THREAD

**Issue by JAMa1994** [topcoder-platform/qa-fun#49]
**Step to reproduce**

Go to the topcoder page 
Tap on filter option
Enter some special characters and "n" of values in keywords/ subtrack / subcommunity sections
Verify any error message is thrown in field or not

**Expected Result**
Field level error message should be displayed in filter options

**Actual result**
Field level error message is not displayed and user is able to enter the special characters ans " n" of numbers in the filter options

**Screenshot**
![image](https://user-images.githubusercontent.com/34433543/75802599-f84b7000-5da2-11ea-9714-6cc30f3750d4.png)

![image](https://user-images.githubusercontent.com/34433543/75802684-1fa23d00-5da3-11ea-8c42-925d38692d9a.png)
**Device/OS/Browser Information:**
Windows 10 / chrome 80.0

**Comment by winterflame** [comment]
Not a bug.
