### ISSUE TITLE
[TCO20-REGIONAL][Web-Chrome] More Details Hover is Not Very Responsive

### ISSUE THREAD

**Issue by trivia79** [topcoder-platform/qa-fun#490]
Repro Steps:
1. Go to https://www.coursera.org/browse
2. Scroll down a little bit before the "Most Popular Certificates" section
3. Hover into the last tile.
4. While the mouse pointer is at the tile, scroll down slowly
5. Notice how the Hover More Details vanished

Actual Result:
Hover More Details vanished when you scroll down

Expected Result:
Hover More Details should not vanished but instead very dynamic and responsive on which the pointer is located

 
Device/Browser Name:
Asus (K401UB); 64-bit OS; x64-based processor /  Chrome Version 84.0.4147.105 (Official Build) (64-bit)

OS Version:
Windows 10 Home Single Language

![image](https://user-images.githubusercontent.com/38703430/89120166-a68c4a80-d4e6-11ea-84b4-215109519110.png)

**Comment by winterflame** [comment]
It's valid, but it came after the submission phase ended. So we will not count it.
