### ISSUE TITLE
Extra margin below clipped

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/qa-fun#493]
**Repro Steps**
1. Go to `https://www.coupons.com/`
2. Add an item
3. Observe the position of Clipped div

**Actual Result**
Has extra margin in bottom.

**Expected Result**
It should not have extra margin in bottom.

**Device/Browser Name**
Device: Macbook Pro MD101
Browser: Chrome Version 84.0.4147.125

**OS Version**
macOS Catalina 10.15.6

**Screenshot/Screencast**
![Screenshot 2020-08-16 at 10 27 23 AM](https://user-images.githubusercontent.com/17943805/90326853-24eaf100-dfab-11ea-8f96-74173aea0089.png)

**Comment by winterflame** [comment]
Hey @anu0012 , the scope has been changed, please have a look: https://apps.topcoder.com/forums/?module=Thread&threadID=960240&start=0
