### ISSUE TITLE
[TCO20-Southern Asia][iOS]  App not work in iOS

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/qa-fun#497]
**Steps to reproduce**

1.  Go to app store https://apps.apple.com/us/app/tutorials-point/id914891263?ls=1
2. Observe app is not proper for iOS 

**Actual Result:** 
App is not work for iOS

**Expected Result:** 
App should be available for iOS

**Screenshot**
![20200816_103624](https://user-images.githubusercontent.com/23450398/90326958-6b8d1b00-dfac-11ea-91cb-2153246d834e.png)

**Device/OS:**  iPhone 7| iOS 13.6.1

**Comment by winterflame** [comment]
out of scope
