### ISSUE TITLE
[Chrome] Late running open for review challanges time remaining is showing None

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#50]
Steps to Reproduce:

Go to https://www.topcoder.com/challenges
Click on "Open for review"
Open one challenge which is running late
Look for "TIME LEFT TO APPLY"
Observe

Expected Result:
Late running open for review challenges time remaining should show 0s

Actual Result:
Late running open for review challenges time remaining is showing "None"

Screenshots or screencast:
![Issue5](https://user-images.githubusercontent.com/51490878/75803763-f5517f00-5da4-11ea-97fb-30e2d6e92a3a.png)
![BrowserInfo_Chrome_ 80 0 3987 116](https://user-images.githubusercontent.com/51490878/75803775-f8e50600-5da4-11ea-9d63-d61663dbb238.png)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/75803776-f8e50600-5da4-11ea-8424-ef1d2265fcfc.png)

Device/OS/Browser Information:
Windows 10,
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by coderkid19** [comment]
Sample link at the time when ticket is submitted.

https://www.topcoder.com/challenges/30116397/review-opportunities

**Comment by winterflame** [comment]
Not a bug.
