### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Get the app phone text can take more than 10 digits

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/qa-fun#503]
**Repro Steps**
1. Go to `https://www.coupons.com/lp/apps`
2. Add any number more than 10 digits
3. Click on `Text me the app` button

**Actual Result**
Can take more than 10 digits.

**Expected Result**
It should not take more than 10 digits.

**Device/Browser Name**
Device: Macbook Pro MD101
Browser: Chrome Version 84.0.4147.125

**OS Version**
macOS Catalina 10.15.6

**Screenshot/Screencast**
![Screenshot 2020-08-16 at 10 35 56 AM](https://user-images.githubusercontent.com/17943805/90326990-d3436600-dfac-11ea-9bda-4e75a58ae581.png)

**Comment by winterflame** [comment]
Hey @anu0012 , the scope is changed since coupons.com not available for most of you, see https://apps.topcoder.com/forums/?module=Thread&threadID=960240&start=0
