### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Text me the app not working

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/qa-fun#504]
**Repro Steps**
1. Go to `https://www.coupons.com/lp/apps`
2. Add any number 
3. Click on `Text me the app` button

**Actual Result**
Doesn't send the link.

**Expected Result**
Should send the download link.

**Device/Browser Name**
Device: Macbook Pro MD101
Browser: Chrome Version 84.0.4147.125

**OS Version**
macOS Catalina 10.15.6

**Screenshot/Screencast**
![Screenshot 2020-08-16 at 10 35 56 AM](https://user-images.githubusercontent.com/17943805/90326990-d3436600-dfac-11ea-9bda-4e75a58ae581.png)

**Comment by winterflame** [comment]
@anu0012 The scope has been changed - see https://apps.topcoder.com/forums/?module=Thread&threadID=960240&start=0
