### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] No error for wrong email

### ISSUE THREAD

**Issue by anu0012** [topcoder-platform/qa-fun#513]
**Repro Steps**
1. Go to `https://www.coupons.com/`
2. Add any item 
3. Click on `Share` button
4. Select email
5. Type any invalid email(i.e hadkehruiew43) without @ or .domain
6. Click Tell a friend and observe

**Actual Result**
Doesn't send and also doesn't show any error.

**Expected Result**
Should show some error message.

**Device/Browser Name**
Device: Macbook Pro MD101
Browser: Chrome Version 84.0.4147.125

**OS Version**
macOS Catalina 10.15.6

**Screenshot/Screencast**
![Screenshot 2020-08-16 at 10 45 08 AM](https://user-images.githubusercontent.com/17943805/90327110-dd199900-dfad-11ea-9e90-403c5056a85a.png)

**Comment by winterflame** [comment]
@anu0012 we're not testing coupons.com, see https://apps.topcoder.com/forums/?module=Thread&threadID=960240&start=0
