### ISSUE TITLE
[Chrome] filter option remains set after Clear filter when user navigates back to Challenge page

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#52]
**Steps to Reproduce:**

Go to https://www.topcoder.com/challenges
Click on "Filters"
Select one start and end date.
Navigate to page other then challenge page.
Come back to challenge page.
Observe filters

**Expected Result:**
 filter option should reset after Clear filter when user navigates back to Challenge page

**Actual Result:**
 filter option remains set after Clear filter when user navigates back to Challenge page

**Screenshots or screencast:**
[Uploading Issue6.zip…]()

![BrowserInfo_Chrome_ 80 0 3987 116](https://user-images.githubusercontent.com/51490878/75805880-a6a5e400-5da8-11ea-9705-288208c7a1d4.png)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/75805898-ad345b80-5da8-11ea-8ab8-c4fb9af15190.png)

**Device/OS/Browser Information:**
Windows 10,
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Video not uploaded successfully.  Same issue as #16 .
