### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome]Unable to delete item

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#522]
Description
Repro Steps:

1. Enter the URL.
2. Login as abanishgiri07@gmail.com / **** (any user)
2. Click on the Office - Any tutorials - Add to cart
3. Try to Remove the cart

Actual Result: Unable to delete the item

Expected Result: Should be able to delete item
[1.zip](https://github.com/topcoder-platform/qa-fun/files/5080024/1.zip)

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

**Comment by winterflame** [comment]
dupe with #516
