### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Error is not handled well if we enter spaces for the search

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/qa-fun#527]
**Reproduction Steps:**

1. Open the app https://www.tutorialspoint.com
2. Login as valid user
3. Go to https://www.tutorialspoint.com/videotutorials/index.php
4. Enter spaces to search
5. Press Enter

**Actual Result:** Error is not handled well if we enter spaces for the search

**Expected Result:** Should display proper validation in the frontend

**Device/OS:** Laptop | Windows 10 (64bit) | Chrome 84.0.4147.125 | Edge 84.0.522.59 | Firefox 79

**Comment by winterflame** [comment]
#501
