### ISSUE TITLE
[Chrome] enable/disable radio button not present for categories "Competitive Programming" and "QA" 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#53]
Steps to Reproduce:

Go to https://www.topcoder.com/challenges
Click on "Tracks"
Observe the categories
Also observe enable/disable radio button

Expected Result:
enable/disable radio button should present for categories "Competitive Programming" and "QA" 

Actual Result:
enable/disable radio button not present for categories "Competitive Programming" and "QA" 

Screenshots or screencast:
![Issue7](https://user-images.githubusercontent.com/51490878/75806368-84f92c80-5da9-11ea-8ad4-0a371dce5146.png)

![BrowserInfo_Chrome_ 80 0 3987 116](https://user-images.githubusercontent.com/51490878/75806373-888cb380-5da9-11ea-8bae-55df036b0e1a.png)
![DeviceInfo_Windows10](https://user-images.githubusercontent.com/51490878/75806377-8a567700-5da9-11ea-99dc-1277e239e2d1.png)

Device/OS/Browser Information:
Windows 10,
Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Similar to #29 , "Competitive Programming" is different with other tracks, no need to add a radio button for it.
