### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] While clicking space then giving any alphabet its searching details

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#536]
Description:- While clicking space then giving any alphabet its searching details

1. Go To https://www.tutorialspoint.com/index.htm

2. Click On Search & Hit Space Bar Three To Four Times Then Give Any Alphabet Hence Observe.

Actual Result:- It's Searching Data

Expected Result:- It Should Not Search Any data.

Device:- Laptop

OS Version:- macOS High Sierra Version 10.13.6 (17G12034)

Browser:- Chrome Version 84.0.4147.125 (Official Build) (64-bit)

Screencast:- 
[1.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/5080031/1.mp4.zip)

**Comment by winterflame** [comment]
This is not a bug - the keyword is trimmed before searching.
