### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] - logos are differnent 

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/qa-fun#559]
Repro Steps

1. Go to URL - https://store.tutorialspoint.com/index.php?page=28
2. scroll down, observe logo is different , one is coloured and and one is black and white

Actual Result
 logo is different

Expected Result
logos should be same, 

Device/Browser Name
Macbook Air / Chrome Version 84.0.4147.125 

OS Version
10.15.2

screen shot
![Screen Shot 2020-08-16 at 11 07 19 AM](https://user-images.githubusercontent.com/57220292/90327403-e35d4480-dfb0-11ea-92f1-debf6a06c54e.png)

**Comment by winterflame** [comment]
This should be as designed.
