### ISSUE TITLE
TCO20-Southern Asia][Web-Chrome] Plus sign is not changed to minus after expand

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/qa-fun#562]
Repro Steps
Open https://www.tutorialspoint.com/videotutorials/subscription.php
Expand the FAQ questions and Observe 

Actual Result
Plus sign is not changed to minus after expand

Expected Result
Plus sign should be changed to minus after expand

Device/Browser Name
laptop/Chrome

OS Version
windows8.1

Screenshot/Screencast
![Screenshot (395)](https://user-images.githubusercontent.com/29044523/90327287-b78d8f00-dfaf-11ea-955b-1911e1d6b35b.png)

**Comment by winterflame** [comment]
#542
