### ISSUE TITLE
[TCO20-Southern Asia][Android] Burger icon in Library doesn't do anything

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/qa-fun#563]
Repro Steps:

        1. Open android app

        2. tap on Library at the bottom bar

        3. tap on burger icon at the top of library screen

        Actual Result:

        nothing happens

        Expected Result:

        should load the menu 

        Device/Browser Name:

        Oneplus 3T/ Android App

        OS Version:

        Android 9

        Screenshot/Screencast: https://drive.google.com/file/d/15fc2OLsWdK9O6CO5cJC3CBqDPTkslGl2/view?usp=sharing

**Comment by winterflame** [comment]
dupe with #535
