### ISSUE TITLE
Unable to Filter based on date range.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#57]
Steps:-
URL : -https://www.topcoder.com/challenges?
1. Login into topcoder.
2. Try to filter based on date range by providing multiple ranges.

Issue : Unable to filter date based on challenges end date due to Search button missing.

Expected Result : Should be able to filter based on Date range.

**Comment by ab668685** [comment]
Browser - Chrome
Device-Laptop
OS-Windows

**Comment by winterflame** [comment]
Missing screenshot and/or screencast.
