### ISSUE TITLE
[TCO20-Southern Asia][Android] Humberger menu not working in library page

### ISSUE THREAD

**Issue by Krishna1507** [topcoder-platform/qa-fun#577]
**Steps to reproduce**

1. Open the to tutorialspoint app
2. Go to the Library section
3. Tap on humberger menu and observe

**Actual Result:** 
Humberger menu not working in Library page

**Expected Result:** 
Humberger menu Should be working

**Screenshot**

[Bug.zip](https://github.com/topcoder-platform/qa-fun/files/5080057/Bug.zip)

**Device/OS:**  OnePlus 7T | Android 10

**Comment by winterflame** [comment]
dupe with #535
