### ISSUE TITLE
TCO20-Southern Asia][Android]search textbox not algined properly

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/qa-fun#578]
Repro Steps
Open App, Click Library.
Click the logo on top and Observe the searh text box

Actual Result
search textbox not algined properly

Expected Result
search textbox should be  algined properly

Device/Browser Name
Mobile realme X2

OS Version
Android 10

Screenshot/Screencast
![WhatsApp Image 2020-08-16 at 11 16 15 AM](https://user-images.githubusercontent.com/29044523/90327546-31267c80-dfb2-11ea-94af-6e831e61ad6f.jpeg)

**Comment by winterflame** [comment]
dupe with #510
