### ISSUE TITLE
Getting Failed to save the filter message

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#58]
Steps:
URL : https://www.topcoder.com/challenge
1. Login to topcoder challenge.
2. Try to give date ranges.
3. Click Save Filter

Actual result : Getting  Failed to save the filter message

Expected Result : Should be able to Save filter

**Comment by ab668685** [comment]
Browser - Chrome
Device-Laptop
OS-Windows

**Comment by winterflame** [comment]
duplicated with #2
