### ISSUE TITLE
TCO20-Southern Asia][Android] Go button is not algined properly

### ISSUE THREAD

**Issue by Vips19** [topcoder-platform/qa-fun#581]
Repro Steps
Open App, Click Library.
click the titorialpoint logo on top
Scroll down to the end and Observe the go button in sending newletter

Actual Result
Go button not algined properly

Expected Result
Go button should be algined properly

Device/Browser Name
Mobile realme X2

OS Version
Android 10

Screenshot/Screencast
![WhatsApp Image 2020-08-16 at 11 19 16 AM](https://user-images.githubusercontent.com/29044523/90327577-7ea2e980-dfb2-11ea-9087-a84cf7174ee2.jpeg)

**Comment by winterflame** [comment]
no alignment issue here.

**Comment by Vips19** [comment]
text not vertically aligned @winterflame
