### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] "Library","Videos", "Q/A", "eBooks" options not shown when window resized to Mobile view.

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#589]
**Repro Steps**
1) https://www.tutorialspoint.com/questions/index.php
2) Observe  "Library","Videos", "Q/A", "eBooks" options
3) Now, resize window to mobile view size
Observe "Library","Videos", "Q/A", "eBooks" option not present in mobile view.

**Actual Result**
"Library","Videos", "Q/A", "eBooks" option not present in mobile view when resized.

**Expected Result**
"Library","Videos", "Q/A", "eBooks" option should be present in mobile view when resized.

**Device/Browser Name**
Laptop
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**OS Version**
Windows 10

**Screenshot/Screencast**

**Comment by coderkid19** [comment]
Video attached in zip file

[7.zip](https://github.com/topcoder-platform/qa-fun/files/5080061/7.zip)

**Comment by coderkid19** [comment]
![ChromeVersion_84 0 4147 125](https://user-images.githubusercontent.com/51490878/90327635-333d0b00-dfb3-11ea-9df3-542bb0a68e43.png)
![Windows10_version](https://user-images.githubusercontent.com/51490878/90327636-346e3800-dfb3-11ea-9928-bd8d76cd187e.png)

**Comment by winterflame** [comment]
We only focus on normal size browser view.
