### ISSUE TITLE
On mouse hover to ongoing challenge of [MM] - no text displayed

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#59]
Steps:-
1. Hit URL - https://www.topcoder.com/challenges
2. Login to URL
3. Goto Ongoing chanllenges [MM]
4. Mouse hover on the MM icon.

Actual result : On Mousehover no text message displayed
Expected Result : Text message should display

**Comment by ab668685** [comment]
browser-chrome
OS- Windows
Laptop

**Comment by winterflame** [comment]
1) Duplicated with #43 .

2) Should provide screenshot and/or screencast.
