### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] - arrow is overlapping the name of tile

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/qa-fun#597]
Repro Steps

1. Go to URL - https://www.tutorialspoint.com/videotutorials/index.php
2. scroll down, arrow is overlapping the name of tile

Actual Result
arrow is overlapping the name of tile

Expected Result
arrow should not overlap the name of tile

Device/Browser Name
Macbook Air / Chrome Version 84.0.4147.125

OS Version
10.15.2

screen shot
![Screen Shot 2020-08-16 at 11 28 36 AM](https://user-images.githubusercontent.com/57220292/90327670-c413e680-dfb3-11ea-9612-a410d503fe70.png)

**Comment by winterflame** [comment]
dupe with #514
