### ISSUE TITLE
Not search challenges when user click on label of challenges

### ISSUE THREAD

**Issue by HongHT** [topcoder-platform/qa-fun#6]
**Reproduction Steps:**
1. Open the url http://www.topcoder.com
2. Login success
3. Open the url https://www.topcoder.com/challenges
4. Click on any label of challenges, ex: “BH”
5. Check result search

**Actual Result:**
List challenges not change when user click on label “BH”
![2](https://user-images.githubusercontent.com/26895101/75686439-d385c880-5cce-11ea-9413-d7ef09f20091.png)

**Expected Result:**
List challenges should be show with keyword “BH”

**Environment:** Lenovo legion, Windows 10

**Environment:** Google Chrome Version 80.0.3987.122

**Comment by winterflame** [comment]
Not a bug.
