### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] "Trending Categories" got vanished when window resized to mobile view and back to original size

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#601]
**Repro Steps**
1) Go to https://www.tutorialspoint.com/questions/index.php
2) Resized window to mobile view width
3) click on three line drop down from  mobile view,  "Trending Categories" drawer appears.
4) click on three line drop down again from  mobile view, "Trending Categories" drawer disappears
5) Maximize windows
Look for  "Trending Categories"
Observe

**Actual Result**
"Trending Categories" got vanished when window resized to mobile view and back to original size

**Expected Result**
"Trending Categories" should not vanish when window resized to mobile view and back to original size

**Device/Browser Name**
Laptop
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**OS Version**
Windows 10

**Screenshot/Screencast**

**Comment by coderkid19** [comment]
[601.zip](https://github.com/topcoder-platform/qa-fun/files/5080069/601.zip)


Attached video in zip format.

**Comment by winterflame** [comment]
mobile view is out of scope
