### ISSUE TITLE
[TCO20-Southern Asia][android] Library hamburger menu is dead link 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/qa-fun#602]
**Repro Steps**
	
1 Open android app 
2. tap on library 
3. try to click hamburger menu 

**Actual Result**

hamburger menu is dead link

**Expected Result**
should show the contents of library (i.e. academic, computer science, digital marketing )
 
**Device/Browser Name**
Android

**OS Version**
7
![android_info](https://user-images.githubusercontent.com/48902251/90327258-6b434e80-dfb1-11ea-92b5-871d1df05eeb.png)

**Screenshot/Screencast**
[bug7.zip](https://github.com/topcoder-platform/qa-fun/files/5080068/bug7.zip)

**Comment by winterflame** [comment]
duplicated
