### ISSUE TITLE
[TCO20-Southern Asia][Web-Edge] When list is expanded the plus icon is not changing to minus icon

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#604]
**Repro Steps**
1. Open the https://www.tutorialspoint.com/videotutorials/subscription.php
2. Now scroll down and go to FAQ
3. Now click on the list and observe
4. The list is expanded but the icon is not changing

**Actual Result** 
The list is expanded but the icon is not changing

**Expected Result**
When list is expanded it should change to minus icon

**Device/Browser Name**
Laptop - Edge

**OS Version**
Windows 10

Screenshot/Screencast
[2020-08-15 10-22-11.zip](https://github.com/topcoder-platform/qa-fun/files/5080071/2020-08-15.10-22-11.zip)

**Comment by winterflame** [comment]
saw this already reported
