### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Two ">" displayed in banner with overlap

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#607]
Description
Repro Steps:

1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2.Click on Top courses link
3. Goto the banner
4. View > icons

Actual Result:Two ">" displayed overlapped

Expected Result:  Two icon should not display with overlapp

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

![image](https://user-images.githubusercontent.com/61318135/90327734-5d42fd00-dfb4-11ea-8f0a-9532ff5e16d5.png)
![image](https://user-images.githubusercontent.com/61318135/90327759-a5fab600-dfb4-11ea-8097-dee4862da9f6.png)

**Comment by winterflame** [comment]
duplicated

**Comment by ab668685** [comment]
Please add with which bug this is duplicate.It will be helpful
