### ISSUE TITLE
[TCO20-Southern Asia][Web-Edge] Error at search option

### ISSUE THREAD

**Issue by tchackerc** [topcoder-platform/qa-fun#608]
Repro Steps
1.Launch app
2.Click on search
3.Enter text
4.Click on search

Actual Result
Error at search option

Expected Result
Search option should work properly

Device/Browser Name
Laptop/Windows10/Edge

OS Version
Windows10

Screenshot/Screencast
![2020-08-16-11-34-24](https://user-images.githubusercontent.com/60475043/90327762-ab580080-dfb4-11ea-9949-9267036f5fd1.png)

**Comment by winterflame** [comment]
similar to #532, special chars not handled
