### ISSUE TITLE
[TCO20-Southern Asia][android] Library >> search box and search icon UI issue 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/qa-fun#612]
**Repro Steps**
	
1 Open android app 
2. tap on library 
3. tap search icon 
4. observe the  search input field and search icon 

**Actual Result**

search input form box is bigger than the search button 

**Expected Result**
search form should be aligned 
 
**Device/Browser Name**
Android

**OS Version**
7
![android_info](https://user-images.githubusercontent.com/48902251/90327258-6b434e80-dfb1-11ea-92b5-871d1df05eeb.png)

**Screenshot/Screencast**
![bug8](https://user-images.githubusercontent.com/48902251/90327787-0559c580-dfb7-11ea-8f81-49975803f2e0.png)

**Comment by winterflame** [comment]
dupe with #510
