### ISSUE TITLE
On Mousehover to search icon - gets text as icon-magnifying-glass

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#62]
Steps:-
Windows /Laptop
Browser - Chrome
URL : https://topgear.topcoder.com/challenges
1. Login into topcoder.
2. Mousehover near MyProfile >> Search icon .
3. View the icon

Actual Result: On Mousehover to search icon - gets text as icon-magnifying-glass
Expected Result : Should get message as Search icon not html text

**Comment by winterflame** [comment]
1) Missing screenshot and/or screencast.
2) This is a UI issue, not a functional bug.
