### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] - error message remains present after going to login screen

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/qa-fun#626]
Repro Steps

1.go to URL - https://store.tutorialspoint.com/category-courses.php?c=critical_thinking
2 go down select create account, enter invalid fields and observe error, now go back to login, and come backto create account, full name error remains present.

Actual Result
full name error remains present 

Expected Result
email error goes out so fullname error should also be removed on going to login screen and coming back to create an account

Device/Browser Name
Macbook Air / Chrome Version 84.0.4147.125

OS Version
10.15.2

screen shot
[Screen Recording 2020-08-16 at 11.47.25 AM.mov.zip](https://github.com/topcoder-platform/qa-fun/files/5080096/Screen.Recording.2020-08-16.at.11.47.25.AM.mov.zip)
![Screen Shot 2020-08-16 at 11 47 42 AM](https://user-images.githubusercontent.com/57220292/90328009-97ad9980-dfb6-11ea-8836-05f125f70a6c.png)

**Comment by winterflame** [comment]
dupe with #611

**Comment by akultalwar89** [comment]
@winterflame  - wont these be considered as different bugs? one is that after entering name it is still showing and one is, either if it is blank - the error remains same.

**Comment by akultalwar89** [comment]
After going to login and coming back here
