### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome]Social icon links are displayed in Headers

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#650]
Steps:

1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2.Click on Tutorial Library any links
3. View the Social link icons

Actual Result: Social icon  links are displayed in Headers

Expected Result: Social links should display in Footers

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

![image](https://user-images.githubusercontent.com/61318135/90328302-fe33b700-dfb8-11ea-9c12-4f3a02cad662.png)

**Comment by winterflame** [comment]
not a bug, this is as designed.
