### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Remove button should remove tha course from the cart

### ISSUE THREAD

**Issue by psharneja** [topcoder-platform/qa-fun#653]
Repro Steps:

        1. open https://www.tutorialspoint.com/
        2. Log in if you have not
        3. click 'Add to Cart' on any course
        4. Now the cart is open, click on Remove next to the course

        Actual Result:

        Page refreshes, with a message that the cart is empty then again shows the same course in the cart

        Expected Result:

       should show empty cart or move to homepage

        Device/Browser Name:

        Macbook Pro/ macOS Catalina/ Chrome 84

        OS Version:

        macOS catalina

        Screenshot/Screencast: https://drive.google.com/file/d/1vf5c-TBXcY5YLcNv-oQ6Kz_738VNgYPI/view?usp=sharing

**Comment by winterflame** [comment]
dupe with #516
