### ISSUE TITLE
[TCO20-Southern Asia] [Web-Chrome] Personal Development Other link - User Interface Issue

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#654]
Description: 
        Repro Steps:
        1. Go to https://www.tutorialspoint.com/excel_vba_online_training/index.asp
        2. Click on the Categories dropdown 
        3. Hover the cursor on Personal Development  
        4. Hover the cursor on “Personal Development Other” subcategory 
  Actual Result:
        Forward arrow is found in “Personal Development Other” subcategory
 Expected Result:
        Forward arrow should not appear in “Personal Development Other”, since there is no subcategory found for “Personal Development Other”
   Device/Browser Name:
        Laptop/ Google Chrome Version 84.0.4147.125
   OS Version:
        Windows 10 / Version 1909

   Screenshot/Screencast: 
 
![image](https://user-images.githubusercontent.com/56633093/90328333-376c2700-dfb9-11ea-9db9-ad466fd4ffef.png)

**Comment by winterflame** [comment]
reported already
