### ISSUE TITLE
[TCO20-Southern Asia][Mobile-Android]Grid icon is not clickable

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#674]
Repro Steps:

1.Login into app
2. Click on Library icon
3. Click on grid icon available near by search

Actual Result: Grid icon is not clickable

Expected Result: Grid icon should be clickable

Device - Samsung A20
[4.zip](https://github.com/topcoder-platform/qa-fun/files/5080155/4.zip)

![image](https://user-images.githubusercontent.com/61318135/90328789-cfb7db00-dfbc-11ea-95ed-b1ed4c87baaf.png)

**Comment by winterflame** [comment]
dupe #602
