### ISSUE TITLE
TCO20-Southern Asia][Mobile-Android]Unable to view app in landscape mode

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#678]
1.Login into the app
2.Try to view the app in Landscape mode

Actual Result: Unable to view app in Landscape mode 

Expected Result: Should be able to view app in landscape mode 
Device -Samsung A20

![image](https://user-images.githubusercontent.com/61318135/90328833-448b1500-dfbd-11ea-9b46-0729db8fc8b4.png)

![image](https://user-images.githubusercontent.com/61318135/90328879-afd4e700-dfbd-11ea-8721-908cec01e0a5.png)

**Comment by winterflame** [comment]
not a bug - this app is for portrait mode only

**Comment by ab668685** [comment]
@winterflame App should be portable for both landscape & portable.Could you please check?
