### ISSUE TITLE
Incorrect Share Icon Text On Challenge Description Page.

### ISSUE THREAD

**Issue by MonicaDevanesi** [topcoder-platform/qa-fun#68]
Reproduction Steps:

1. Navigate to URL - https://www.topcoder.com/challenges 
2. Login with a valid user.
3. Navigate to Challenge '96h Ognomy Phase 2 Mobile App React Native UI Challenge #2'
4. View Share Options.

Actual result : 
Icon text is displayed as icon facebook , icon twitter, icon print , icon email and icon +

Expected Result : 
Icon Text must be displayed as Facebook , Twitter , Print , Email etc.,

Device/OS: Desktop | Windows 10 (64bit)

Browser : Google Chrome
Version : 80.0.3987.122

![image](https://user-images.githubusercontent.com/61777192/75863311-42c20080-5e26-11ea-9341-be53a02323b9.png)

![image](https://user-images.githubusercontent.com/61777192/75863332-4b1a3b80-5e26-11ea-9b1d-da75754990b3.png)

![image](https://user-images.githubusercontent.com/61777192/75863369-58cfc100-5e26-11ea-89da-f5e31f3e14fc.png)

**Comment by winterflame** [comment]
Not a functional bug.
