### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] - Plus + sign should be - when open

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/qa-fun#696]
Repro Steps

1.Go to URL -https://www.tutorialspoint.com/videotutorials/subscription.php
2.Observe the + sign remains + when opened the link

Actual Result
Observe the + sign remains + when opened the link

Expected Result
it should show as - when opened

Device/Browser Name
Macbook Air / Chrome Version 84.0.4147.125

OS Version
10.15.2

screen shot
![Screen Shot 2020-08-16 at 1 06 39 PM](https://user-images.githubusercontent.com/57220292/90329320-77cfa300-dfc1-11ea-9ec4-d0490e670c62.png)

**Comment by winterflame** [comment]
already reported
