### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Go button & NewsLetter fields not aligned properly

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#697]
Repro Steps:

1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2. Goto bottom of the page
3. View button Go  & NewsLetter fields

Actual Result:  Go button & NewsLetter fields not aligned properly

Expected Result: Go button & NewsLetter fields should aligned properly

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

![image](https://user-images.githubusercontent.com/61318135/90329325-7f8f4780-dfc1-11ea-9321-3abb81d33cb1.png)

**Comment by winterflame** [comment]
No alignment issue here.
