### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] - the main page highlight is showing random books text

### ISSUE THREAD

**Issue by akultalwar89** [topcoder-platform/qa-fun#702]
Repro Steps

1.Go to URL -https://www.tutorialspoint.com/videotutorials/subscription.php
2.on hover observe it is showing normal text, and other pages shows page header 

Actual Result
the main page highlight is showing random books text

Expected Result
it should show tutorial point or page header instead of random text

Device/Browser Name
Macbook Air / Chrome Version 84.0.4147.125

OS Version
10.15.2

screen shot
![Screen Shot 2020-08-16 at 1 11 46 PM](https://user-images.githubusercontent.com/57220292/90329406-4a372980-dfc2-11ea-86e9-6fa285e9ef9b.png)

[Screen Recording 2020-08-16 at 1.11.25 PM.mov.zip](https://github.com/topcoder-platform/qa-fun/files/5080193/Screen.Recording.2020-08-16.at.1.11.25.PM.mov.zip)

**Comment by winterflame** [comment]
not a bug, this is intentional.
