### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Lot of unused empty space in list dropdown 

### ISSUE THREAD

**Issue by coderkid19** [topcoder-platform/qa-fun#705]
**Repro Steps**
1) Go to https://store.tutorialspoint.com/index.php?page=1
2) Click on Categories
3) Drop down appears 
Observe

**Actual Result**
Lot of unused empty space in list dropdown 

**Expected Result**
Unused empty space should not be present in list drop down

**Device/Browser Name**
Laptop
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

**OS Version**
Windows 10

**Screenshot/Screencast**

**Comment by coderkid19** [comment]
![705](https://user-images.githubusercontent.com/51490878/90329457-b1ed7480-dfc2-11ea-94ff-e079f8ff752c.png)

![ChromeVersion_84 0 4147 125](https://user-images.githubusercontent.com/51490878/90329459-b74abf00-dfc2-11ea-908d-2bf3ce77ae50.png)

![Windows10_version](https://user-images.githubusercontent.com/51490878/90329462-b9ad1900-dfc2-11ea-97e7-56a19e813355.png)

**Comment by winterflame** [comment]
dupe with #498
