### ISSUE TITLE
[Open for Review] Challenges loading time is more than 5 sec

### ISSUE THREAD

**Issue by Jacob15** [topcoder-platform/qa-fun#71]
Reproduction Steps:

1.Navigate to URL - https://www.topcoder.com/challenges
2.Login with a valid user.
3.Navigate to Open for Review
4. Observe the Challenge loading time
5. Challenges loading time is more than 5 sec.

Actual result :
Challenges loading time is more than 5 sec.

Expected Result :
Challenges loading should be within 5 sec

Device/OS: Desktop | Windows 10 (64bit)

Browser : Google Chrome
Version : 80.0.3987.122
[Bug3.zip](https://github.com/topcoder-platform/qa-fun/files/4286713/Bug3.zip)

**Comment by winterflame** [comment]
It's about the performance and related to network speed, not a functional bug.
