### ISSUE TITLE
Sort by 'Provisional' values are inconsistent

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/qa-fun#72]
https://www.screencast.com/t/o15mspQkJ

**URL:**
https://www.topcoder.com/challenges/30092303?tab=submissions

**Reproduction Steps:**

1. Open https://www.topcoder.com and Login as a valid user
2. Go to 'Ongoing challenges'
3. Click 'SingleCell - Trajectory Inference Methods' > https://www.topcoder.com/challenges/30092303?tab=submissions
4. Click Submissions tab
5. Sort the 'Provisional' A-Z
6. Sort the 'Provisional' Z-A

**Expected Result:** Sorting should be consistent

**Actual Result:** Sort the list by A-Z will list the '0' as first and (x) as second, then after user sort the list by Z-A the last it (x) and then the '0'

**Device/OS:** Laptop | Windows 10 (64bit)

**Browser Information:** Google Chrome  80.0.3987.122

**Comment by winterflame** [comment]
Sorting in an ascending order:

![ascending](https://user-images.githubusercontent.com/4590317/76091890-66897000-5ff9-11ea-8180-4a90961c4fb1.jpg)


Sorting in an descending order:
![descending](https://user-images.githubusercontent.com/4590317/76091949-85880200-5ff9-11ea-8cf5-20584ab9595f.jpg)
