### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome]- No "-" icon for collapse in Frequently asked question

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#720]
Repro Steps:

1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2.Click on Library
3.Click on Subscribe to Premium
4. Goto Frequently asked question
5. Click on any question + icon Expand /Collapse 

Actual Result: No "-" icon for collapse in Frequently asked question

Expected Result: "-" Should be available for collapse 

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

[8.zip](https://github.com/topcoder-platform/qa-fun/files/5080241/8.zip)

**Comment by winterflame** [comment]
duplicated
