### ISSUE TITLE
 [TCO20-Southern Asia][Android-Chrome] No more padding for large text in 'View more Courses' teaser

### ISSUE THREAD

**Issue by shcul333** [topcoder-platform/qa-fun#725]
Reproduction Steps:
![no_padding_for_large_text](https://user-images.githubusercontent.com/69748263/90329988-17436480-dfc7-11ea-9dc5-bee6edd94992.jpg)
    

1. Open the app
2. Scroll to Latest Courses section with Courses teaser/sliders with course " Microsoft Teams: Discover...."

Actual Result: Large text heading of course touches the edge of container

Expected Result: Should have enough padding for large text to avoid touching edge of container

Device/OS: Mobile | MI A3 | Android 9.0

**Comment by winterflame** [comment]
@shcul333 We don't test on mobile browsers.
