### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Panels are squeezed together

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#726]
Repro Steps
Go to https://www.tutorialspoint.com/index.htm
Scroll to view featured course 
Click on IT or other category

Actual Result
Panels are squeezed together

Expected Result
Should have enough space between the panels

Device/Browser Name
Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
![Snapshot 2020-08-16 13 47 34](https://user-images.githubusercontent.com/32645062/90329998-25918080-dfc7-11ea-93c2-a7a7f97d1918.png)
[2020-08-16 13-42-44.zip](https://github.com/topcoder-platform/qa-fun/files/5080256/2020-08-16.13-42-44.zip)

**Comment by winterflame** [comment]
@venkygot we don't test on mobile browsers, so mobile view is out of scope.
