### ISSUE TITLE
[Windows-Chrome]: Submit page and blank page appears when logging in and logging out

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/qa-fun#73]
Bug Title: Submission page opens when logged out then turns to blank when refreshed
Steps to Reproduce:
1.Log in to any registered account.
2.Open two tabs to a registered challenge.
3.Open one of the tabs and Log out.
4.Open the other tab and click on submit button at the top right.
5.Refresh the page.
Expected Result:
Submit page shouldn't open and shouldn't show blank page after refresh.
Actual Result:
A message appears to ask for Logging in first to access submit panel after clicking on submit button.
Screenshots or screencast:
https://drive.google.com/file/d/1_RjYPsf8obkFvZT6hharYnBWxhw84FUj/view?usp=sharing
Device/OS/Browser Information:
Windows 10/ChromeDevice/OS: Desktop | Windows 10 (64bit)
Browser : Google Chrome
Version : 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
@shimaaahmedd Unable to view the screenshots or screencast:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/4590317/76092210-ff1ff000-5ff9-11ea-8c36-6616084ead05.png">

Can you share it in the google drive?

**Comment by shimaaahmedd** [comment]
> @shimaaahmedd Unable to view the screenshots or screencast:
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/4590317/76092210-ff1ff000-5ff9-11ea-8c36-6616084ead05.png">
> 
> Can you share it in the google drive?

Done Editing the link, now accessible on google drive.
