### ISSUE TITLE
[TCO20-Southern Asia][Web-Firefox] overlapping of title

### ISSUE THREAD

**Issue by Peppa-2016** [topcoder-platform/qa-fun#730]
Repro Steps:

        1. Go to https://www.tutorialspoint.com/index.htm

        2. Refresh and check under latest courses

       

        Actual Result:Arrow is overlapping over the image/title of the course

        Expected Result: Arrow should not overlap over the image/title of the course

 
        Device/Browser Name: Firefox

        Enter the device/browser name here.

          Screenshot/Screencast:
![overlap](https://user-images.githubusercontent.com/60426529/90330037-68535880-dfc7-11ea-8dad-a90b3712fd5f.jpg)

 

       OS Version: Windows 7
![About Firefox](https://user-images.githubusercontent.com/60426529/90330021-4d80e400-dfc7-11ea-9570-e01ef75aa9db.jpg)

**Comment by winterflame** [comment]
dupe with #514
