### ISSUE TITLE
[TCO20-Southern Asia][Android-Chrome]  'View more Courses' slider teaser under 'Top Courses' scrolling is not smooth.

### ISSUE THREAD

**Issue by shcul333** [topcoder-platform/qa-fun#732]
Reproduction Steps:
    Open the app
    Scroll to Latest Courses section with Courses teaser/sliders .
    Try to slide through sliders horizontally

Screencast :- https://drive.google.com/file/d/18OmmpF2Anm7Oy3YtpnxrjfKmb_YYzkmL/view?usp=sharing

Actual Result: Scrolling right-left by touch on mobile not smooth

Expected Result: sliding should be smooth.

Device/OS: Mobile | MI A3 | Android 9.0

**Comment by winterflame** [comment]
mobile browser is out of scope.
