### ISSUE TITLE
[TCO20-Southern Asia][Android-Chrome] Showing horizontal slider content in vertical view for few seconds on navigating back from course page.

### ISSUE THREAD

**Issue by shcul333** [topcoder-platform/qa-fun#735]
Reproduction Steps:
Open the app
Scroll to Latest Courses section with Courses teaser/sliders .
Observe sliders showing content horizontally
Select any course.
navigate back to previous page.
Observe horizontal slider showing for sometime in vertical.

Screencast :- https://drive.google.com/file/d/18OmmpF2Anm7Oy3YtpnxrjfKmb_YYzkmL/view?usp=sharing

Actual Result: Slider shows up in vertical

Expected Result: Transition should be smooth without showing content vertical.

Device/OS: Mobile | MI A3 | Android 9.0

**Comment by winterflame** [comment]
mobile browser is out of scope.

**Comment by shcul333** [comment]
@winterflame  in Forum it was mentioned all platforms are open.
