### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Course description overlap on image and hours area

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#738]
Repro Steps
Go to https://www.tutorialspoint.com/videotutorials/index.php
Scroll side ways to see courses with description running over

Actual Result
Long description runs over the screen.

Expected Result
Should be wrapped with tooltip or something similar

Device/Browser Name
Laptop/ Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
[2020-08-16 14-01-15.zip](https://github.com/topcoder-platform/qa-fun/files/5080281/2020-08-16.14-01-15.zip)

**Comment by winterflame** [comment]
mobile view is out of scope.
