### ISSUE TITLE
 [TCO20-Southern Asia][Android-Chrome] Bottom contacts section not evenly spaced leaving hugh empty space at right

### ISSUE THREAD

**Issue by shcul333** [topcoder-platform/qa-fun#740]
Reproduction Steps:
Open the app
Now switch to 'Desktop View'
Scroll down to end section.
Observe 2nd last section is not evenly placed leaving empty space on right unlike desktop site.

Screencast :- https://drive.google.com/file/d/18OtssGY1X3hilabMNonOvuyVMokQJ32B/view?usp=sharing

Actual Result: EMpty space at bottom right

Expected Result: Content should be evenly spaced w/o empty space

Device/OS: Mobile | MI A3 | Android 9.0

**Comment by winterflame** [comment]
mobile browser is out of scope.

**Comment by shcul333** [comment]
@winterflame  in Forum it was mentioned all platforms are open.
