### ISSUE TITLE
[TCO20-Southern Asia][Web-Firefox] When clicking on Login the email and password textfield already showing red (error) means they are validating before we enter something

### ISSUE THREAD

**Issue by rajanmourya** [topcoder-platform/qa-fun#741]
**Repro Steps**
1. Open the https://www.tutorialspoint.com/index.htm
2. Now click on login
3. Observe the login fields are already showing red (they are already validated)

**Actual Result** 
Observe the login fields are already showing red (they are already validated)

**Expected Result**
The login field must be validated when we submit

**Device/Browser Name**
Laptop - Firefox

**OS Version**
Windows 10

Screenshot/Screencast
[2020-08-15 10-22-11.zip](https://github.com/topcoder-platform/qa-fun/files/5080288/2020-08-15.10-22-11.zip)

**Comment by winterflame** [comment]
duplicated
