### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Browsing courses loading incorrectly

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#742]
Repro Steps
Go to https://www.tutorialspoint.com/videotutorials/index.php
Under latest courses with Development tab
Flick side ways to browse course and observe

Actual Result
On flick two course that shown are replaced with something else.

Expected Result
Should be consistant and predictable.

Device/Browser Name
Iphone X/ Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
[2020-08-16 14-08-47.zip](https://github.com/topcoder-platform/qa-fun/files/5080290/2020-08-16.14-08-47.zip)

**Comment by winterflame** [comment]
mobile view is out of scope.
