### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Deleted item appears again in Shopping cart

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/qa-fun#744]
[24.zip](https://github.com/topcoder-platform/qa-fun/files/5080295/24.zip)

**Reproduction Steps:**

1. Open the app https://www.tutorialspoint.com/index.htm
2. Login as valid user
3. Scroll down and click on the Add to cart from a course
4. When the user is in the shopping cart > click Remove
5. Observe

**Actual Result:** Deleted item appears again in Shopping cart

**Expected Result:** Should remove the item from the cart

**Device/OS:** Laptop | Windows 10 (64bit) | Chrome 84.0.4147.125 | Edge 84.0.522.59 | Firefox 79

**Comment by winterflame** [comment]
duplicated
