### ISSUE TITLE
 [TCO20-Southern Asia][Android] 'More' button is not aligned well in mobile app

### ISSUE THREAD

**Issue by shcul333** [topcoder-platform/qa-fun#747]
Reproduction Steps:

    Open the mobile app
    Swipe right and check the more button

Screencast :  https://drive.google.com/file/d/18UAGh2YKJCRCZkSi36DULuRGiXfYenKj/view?usp=sharing

Actual Result:'More' button is not aligned well

Expected Result: Should center align within the tile

Device/OS: Mobile | Mi A3 | Android 9.0

**Comment by winterflame** [comment]
duplicated

**Comment by shcul333** [comment]
This is for mobile application. can you share duplicate issue# ? 
Thanks
