### ISSUE TITLE
[Windows-Chrome]: unregister button still appears after logging out.

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/qa-fun#75]
Bug Title: An error appears when clicking on Unregister button after logging out from a registered account.
Steps to Reproduce:
1.Log in to any registered account.
2.Open a registered challenge.
3.Copy the URL Link for the challenge
3.Log out.
4.Paste the URL you just copied it and navigate to the URL.
5.Click unregister button.
Expected Result:
Register button should appear instead of unregister button or a Login request should appear.
Actual Result:
Unregister button still appears and and error popup appears after clicking on it.
Screenshots or screencast:
https://drive.google.com/file/d/1iXKoY44KVqXpXOLa2s6ZKJRqGTy1VAyF/view?usp=sharing
Device/OS: Desktop | Windows 10 (64bit)
Browser : Google Chrome
Version : 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
@shimaaahmedd Can you share it in the google drive?

**Comment by shimaaahmedd** [comment]
yes sure, sorry for that

**Comment by shimaaahmedd** [comment]
> @shimaaahmedd Can you share it in the google drive?

Done Editing the link, now accessible on google drive.
