### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Unable to view all categories

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#750]
Repro Steps
Go to https://www.tutorialspoint.com/videotutorials/index.php
Select Categories dropdown in landscape mode

Actual Result
Not all dropdown values are visible on sliding down

Expected Result
Should list all the values on sliding down.

Device/Browser Name
Laptop/ Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
[2020-08-16 14-17-27.zip](https://github.com/topcoder-platform/qa-fun/files/5080309/2020-08-16.14-17-27.zip)

**Comment by winterflame** [comment]
mobile view out of scope
