### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Course list view isn't loading properly

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#756]
Repro Steps
Go to https://www.tutorialspoint.com/videotutorials/category/design/1
Slide down to view the courses

Actual Result
Empty space can be seen 

Expected Result
Available course should take these empty spaces.

Device/Browser Name
Iphone X (landscape mode)/ Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
[2020-08-16 14-21-32.zip](https://github.com/topcoder-platform/qa-fun/files/5080312/2020-08-16.14-21-32.zip)

**Comment by winterflame** [comment]
mobile view not in scope
