### ISSUE TITLE
 [TCO20-Southern Asia][Android] Search box flicking on click

### ISSUE THREAD

**Issue by shcul333** [topcoder-platform/qa-fun#757]
Steps to reproduce

    Open the to tutorialspoint app
    Go to the search section
    Click on search box
    Observe search text box flicking showing back button in btw

Screencast : https://drive.google.com/file/d/18ZTDgwvNLMFMKtZQouXbo1iey52zJ2UV/view?usp=sharing

Actual Result:  Search box flicking showing intermediate another UI

Expected Result: Search box should work smoothly

**Comment by winterflame** [comment]
duplicated
