### ISSUE TITLE
[Windows-Chrome]: Register button appears for projects opened for review.

### ISSUE THREAD

**Issue by shimaaahmedd** [topcoder-platform/qa-fun#76]
Bug Title: Register button is enabled for some projects opened for review.
Steps to Reproduce:
1.Login with valid account.
2.Navigate to https://www.topcoder.com/challenges?
3.Open "Open for review" tab at the right side of the page.
4.Open any random challenge for example "Zappier TC Module Integration with Webhook"
5.Click Register.
Expected Result:
Register button should be disabled, user cannot register and deadline for review phase should appear(0s).
Actual Result:
Register button is enabled, user is able to register and there is a deadline for registration phase.
Screenshots or screencast:
https://drive.google.com/file/d/1NYLn8UhXozGJco33XXbLEJBnARuxtwGE/view
Device/OS: Desktop | Windows 10 (64bit)
Browser : Google Chrome
Version : 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
@shimaaahmedd Can you share it in the google drive?

**Comment by shimaaahmedd** [comment]
> @shimaaahmedd Can you share it in the google drive?

Done Editing the link, now accessible on google drive.

**Comment by winterflame** [comment]
This is not a bug. "Open for review" means that the reviewers can apply for review positions. It does not mean the challenge is in the "Review" phase.
