### ISSUE TITLE
  [TCO20-Southern Asia][Web-Chrome]  Selected Reading Left panel missing blue background color

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#761]
1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2.Login as any registered user
3. Goto bottom of page Tutorial Library
4. Click on any link - redirects to new tab
5. View Selected Reading Left pannel border

Issue :  Selected Reading Left panel missing blue background color

Expected Result : Selected Reading Left panel should display in blue color

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

![image](https://user-images.githubusercontent.com/61318135/90330742-dc442f80-dfcc-11ea-8e68-a0d9b9dbc382.png)

**Comment by winterflame** [comment]
duplicated
