### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Click on Previous will go to the last page

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/qa-fun#762]
[25.zip](https://github.com/topcoder-platform/qa-fun/files/5080321/25.zip)

**Reproduction Steps:**

1. Open the app https://www.tutorialspoint.com/index.htm
2. Login as valid user
3. Go to https://www.tutorialspoint.com/videotutorials/index.php
4. Click Others and Entroll for a FREE course "wedding_photography" - https://www.tutorialspoint.com/wedding_photography_tips_tricks_and_ideas_for_amazing_photos/introduction.asp
5. Now click 'Start' button 
6. Now you are on the first page
7. Click Previous

**Actual Result:**  'Coupon code' is not clearing after it is validated as invalid

**Expected Result:** Should clear the code

**Device/OS:** Laptop | Windows 10 (64bit) | Chrome 84.0.4147.125 | Edge 84.0.522.59 | Firefox 79

**Comment by winterflame** [comment]
Actual Result: 'Coupon code' is not clearing after it is validated as invalid

Expected Result: Should clear the code

not matching the title
