### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Sliding on the Categories dropdown is sliding the background page

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#765]
Repro Steps
Go to https://www.tutorialspoint.com/videotutorials/teach-with-us.php#faq
Open Categories dropdown
Slide the dropdown and observe

Actual Result
Background is sliding instead of dropdown.

Expected Result
Should work as expected

Device/Browser Name
IPhone X/ Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
[2020-08-16 14-31-44.zip](https://github.com/topcoder-platform/qa-fun/files/5080324/2020-08-16.14-31-44.zip)

**Comment by winterflame** [comment]
mobile view out of scope
