### ISSUE TITLE
[TCO20-Southern Asia] [Web-Firefox] Banner forward arrow - User Interface Issue

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#771]
Description: 
        Repro Steps:
        1. Go to https://www.tutorialspoint.com/videotutorials/latest-courses.php
        2. Observe the top banner in this page
        3. Click on forward arrow present at the right side on the banner
  Actual Result:
        Two arrow symbols are found at the right side on the banner
   Expected Result:
        Only one forward arrow should present at the right side on the banner
   Device/Browser Name:
        Laptop/ Firefox 79.0 (64-bit)
   OS Version:
        Windows 10 / Version 1909
   Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/56633093/90330934-5e812380-dfce-11ea-8513-b03a6b2e58ef.png)

**Comment by winterflame** [comment]
duplicated
