### ISSUE TITLE
[TCO20-Southern Asia] [Web-Firefox] Personal Development Other link - User Interface Issue

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#777]
Repro Steps:
        1. Go to https://www.tutorialspoint.com/excel_vba_online_training/index.asp
        2. Click on the Categories dropdown 
        3. Hover the cursor on Personal Development  
        4. Hover the cursor on “Personal Development Other” subcategory 
  Actual Result:
        Forward arrow is found in “Personal Development Other” subcategory
 Expected Result:
        Forward arrow should not appear in “Personal Development Other”, since there is no subcategory found for “Personal Development Other”
   Device/Browser Name:
        Laptop/ Firefox 79.0 (64-bit)
   OS Version:
        Windows 10 / Version 1909

   Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/56633093/90331068-8e7cf680-dfcf-11ea-853b-57b1e06dade8.png)

**Comment by winterflame** [comment]
duplicated
