### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] : FAQ expanded view still shows + sign

### ISSUE THREAD

**Issue by satkanhub** [topcoder-platform/qa-fun#783]
**Reproduction Steps:**
- Goto https://www.tutorialspoint.com/videotutorials/teach-with-us.php#faq
- Click on a FAQ question
- Observe the page

**Actual Result:**
Expanded view still shows + sign

**Expected Result:** 
Expanded view should show - sign

**Device/Browser Name:** 
Desktop Chrome 84.0.4147.125

**OS Version:** 
Windows 10 Home

**Screenshot/Screencast:** 
[26.zip](https://github.com/topcoder-platform/qa-fun/files/5080349/26.zip)

**Comment by winterflame** [comment]
duplicated
