### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Canceling payment on checkout is taking me back to login screen

### ISSUE THREAD

**Issue by venkygot** [topcoder-platform/qa-fun#787]
Repro Steps
Go to https://www.tutorialspoint.com/videotutorials/index.php
Add two course to the cart
Login with account details
Click on checkout and cancel the payment
Click on go back to cart

Actual Result
Application asks for relogin when infact user already logged in

Expected Result
Should not ask for relogin

Device/Browser Name
Iphone X/ Chrome Version 84.0.4147.125 (Official Build) (64-bit)

OS Version
Windows 10 home

Screenshot/Screencast
[2020-08-16 14-55-31.zip](https://github.com/topcoder-platform/qa-fun/files/5080366/2020-08-16.14-55-31.zip)

**Comment by winterflame** [comment]
mobile view out of scope
