### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome]No message displayed on Mousehover on Logout link

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#796]
1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2.Login as any registered user
3.Click on Profile icon
4. Mousehover on Logout

Actual Result: No message displayed

Expected Result: Should display as Logout

Device/Browser Name: Chrome Version 84.0.4147.125 (Official Build) (64-bit) - USED
Firefox - 79.0 (64-bit)
Safari - Version 84.0.522.59

OS Version : Windows 10

![image](https://user-images.githubusercontent.com/61318135/90331446-efa5c980-dfd1-11ea-9652-51cf421296ca.png)

**Comment by winterflame** [comment]
not needed, it's self explanatory.

**Comment by ab668685** [comment]
@winterflame each links are self explanatory .But still mousehover test is provided.Therefore this is a miss.Logout text should appear
