### ISSUE TITLE
[Web-Firefox] Please Enter Value Should Not Be There For How Can We Help You

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/qa-fun#8]
1. Go To https://www.topcoder.com/challenges?bucket=reviewOpportunities

2. Login With Valid ID

3. Scroll Down Mouse To Below At Support & Try To Fill The Details How Can We Help You & Delete It.

4. Then Click On send.

5. See Screencast & Observe
[Pl.mp4.zip](https://github.com/topcoder-platform/qa-fun/files/4275999/Pl.mp4.zip)

6. Expected Result: Please Enter Query Should Be There.

7. Actual Result: Its Showing Please Enter Value.

8. Device: Laptop

9. OS: MacOs
[Mac Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4276004/Mac.Version.png.zip)

10. Browser:
[Firefox Version.png.zip](https://github.com/topcoder-platform/qa-fun/files/4276006/Firefox.Version.png.zip)

**Comment by winterflame** [comment]
Not a bug.
