### ISSUE TITLE
[TCO20-Southern Asia][Web-Firefox] enter description error message is blocked by text field 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/qa-fun#801]
**Repro Steps**
	
1 hhttps://www.tutorialspoint.com/videotutorials/user_course.php
2. in put values in required field  and leave the course description field empty 
3. click on save and observe

**Actual Result**
error message is hidden by text box  
**Expected Result**
should be clearly 
visible 

**Device/Browser Name**

Laptop /Firefox

**OS Version**

79.0 (64-bit)
**Screenshot/Screencast**
![bug34](https://user-images.githubusercontent.com/48902251/90331583-655f6480-dfd5-11ea-92cd-6f0b49999ec2.png)

**Comment by winterflame** [comment]
duplicated
