### ISSUE TITLE
[TCO20-Southern Asia][Web-Firefox]   Course name and tag line accepts white spaces 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/qa-fun#804]
**Repro Steps**
	
1 hhttps://www.tutorialspoint.com/videotutorials/user_course.php
2. in put white spaces on course name and tag line 
3. save 

**Actual Result**
able to save white spaces successfully 
**Expected Result**
app should not accept white spaces 

**Device/Browser Name**

Laptop /Firefox

**OS Version**

79.0 (64-bit)
**Screenshot/Screencast**
[bug35.zip](https://github.com/topcoder-platform/qa-fun/files/5080392/bug35.zip)

**Comment by winterflame** [comment]
duplicated
