### ISSUE TITLE
[TCO20-Southern Asia] [Android] strike out line

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#808]
Repro Steps:
        1. Open “Tutorialspoint” app in android mobile
        2. In home page scroll down and click on “More” link under “LATEST COURSES”
        3. Observe the strike out line on the original price of a Course
  Actual Result:
        Excessive strike out line is found on the original price of a Course
 Expected Result:
        Excessive strike out line should not appear on the original price of a Course   
Device/Browser Name:
        Android mobile
   OS Version:
        Android 10
 
![image](https://user-images.githubusercontent.com/56633093/90331707-41e7ea00-dfd4-11ea-9497-c4b405f9d7bb.png)

   Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/56633093/90331711-46ac9e00-dfd4-11ea-9b16-e23972aa2b84.png)

**Comment by winterflame** [comment]
not a bug
