### ISSUE TITLE
Bug about the color of the "?" icon on the right side of a detail page

### ISSUE THREAD

**Issue by fanwenlin** [topcoder-platform/qa-fun#81]
Bug Title: 
In a detail page of a challenge, if you click the left-arrow on the left-top of the page and then click into the same challenge, the color of the last "?" icon on the right side will turn into a color which is lighter than the normal

Steps to Reproduce:
1. Click into a challenge
2. Click the left-arrow on the left-top of the page and back to the main menu
3. Click into the same challenge again

Expected Result:
The color of the icon will not be changed.
![image](https://user-images.githubusercontent.com/17265932/75986119-738a5e80-5f28-11ea-9959-e1ce53fc21e5.png)

Actual Result:
The color was changed into a lighter green.

Screenshots or screencast:
![image](https://user-images.githubusercontent.com/17265932/75986227-a5032a00-5f28-11ea-8416-417fa0a34de0.png)

Device/OS/Browser Information:
Device: Dell Inspiron 7472
OS: Windows 10 Enterprise 19035.1000
Browser: Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by winterflame** [comment]
Not a functional bug, it's a UI issue.
