### ISSUE TITLE
[TCO20-Southern Asia] [Web-Edge] Banner forward arrow 

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#812]
Repro Steps:
        1. Go to https://www.tutorialspoint.com/videotutorials/latest-courses.php
        2. Observe the top banner 
        3. Click on forward arrow present at the right side on the banner
  Actual Result:
        Two arrow symbols are found at the right side on the banner
   Expected Result:
        Only one forward arrow should present at the right side on the banner
   Device/Browser Name:
        Laptop/ Microsoft Edge 44.18362.449.0
   OS Version:
        Windows 10 / Version 1909
   Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/56633093/90331838-60021a00-dfd5-11ea-9c82-d1da9dfc20f8.png)

**Comment by winterflame** [comment]
dupe
