### ISSUE TITLE
[TCO20-Southern Asia] [Web-Edge] Up arrow - User Interface Issue

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#818]
Repro Steps:
        1. Go to https://www.tutorialspoint.com/mastering_value_based_pricing/index.asp
        2. Click on the Categories dropdown 
        3. observe the arrow symbol next to categories in the heading
  Actual Result:
        Down arrow is shown after clicking the Categories dropdown
   Expected Result:
        Up arrow should be shown after clicking the Categories dropdown
   Device/Browser Name:
        Laptop/ Microsoft Edge 44.18362.449.0
   OS Version:
        Windows 10 / Version 1909

   Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/56633093/90331872-aa839680-dfd5-11ea-8495-b5e037733635.png)

**Comment by winterflame** [comment]
dupe
