### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Currency selected by user is not saved/maintained for the session

### ISSUE THREAD

**Issue by mmmengg-dev** [topcoder-platform/qa-fun#820]
Repro Steps:

1. Go to -> https://store.tutorialspoint.com/
2. Select some e-books -> click on 'Cart'
3. On 'Cart' page user changes the currency from $ to Indian Rupees
4. User again goes back to eBooks section
5. Notice eBooks section still displays currency in $ format although user has opted for Rupees.

Actual Result:
eBooks section displays currency in $ format although user has opted for Rupees as currency in 'Cart' section

Expected Result:
Currency type should be maintained in the session

Device/Browser Name:
Chrome-Version 84.0.4147.125 (Official Build) (64-bit)

OS Version:
Windows 8.1 64-bit Operating System

Screenshot/Screencast: 
[CurrencyNotMainained.zip](https://github.com/topcoder-platform/qa-fun/files/5080406/CurrencyNotMainained.zip)

**Comment by winterflame** [comment]
dupe
