### ISSUE TITLE
[TCO20-Southern Asia] [Web-Edge] Personal Development Other link 

### ISSUE THREAD

**Issue by manju055** [topcoder-platform/qa-fun#821]
Description: 
        Repro Steps:
        1. Go to https://www.tutorialspoint.com/excel_vba_online_training/index.asp
        2. Click on the Categories dropdown 
        3. Hover the cursor on Personal Development  
        4. Hover the cursor on “Personal Development Other” subcategory 
  Actual Result:
        Forward arrow is found in “Personal Development Other” subcategory
 Expected Result:
        Forward arrow should not appear in “Personal Development Other”, since there is no subcategory found for “Personal Development Other”
   Device/Browser Name:
        Laptop/ Microsoft Edge 44.18362.449.0
   OS Version:
        Windows 10 / Version 1909

   Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/56633093/90331916-fc2c2100-dfd5-11ea-820b-24a870191040.png)

**Comment by winterflame** [comment]
dupe
