### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] UI issue on the To date section in the filter

### ISSUE THREAD

**Issue by codejamtc** [topcoder-platform/qa-fun#826]
![image](https://user-images.githubusercontent.com/42398485/90331992-a5dfc380-df7e-11ea-96c7-30326d5db41c.png)

**Reproduction Steps:**

1. Open the app https://www.tutorialspoint.com/index.htm
2. Login as valid user (Switch to Instructor)
3. Go to https://www.tutorialspoint.com/videotutorials/video_sales.php?mode=I
4. Click Filter

**Actual Result:**  UI issue on the To date section in the filter

**Expected Result:** Should align properly

**Device/OS:** Laptop | Windows 10 (64bit) | Chrome 84.0.4147.125 | Edge 84.0.522.59 | Firefox 79

**Comment by codejamtc** [comment]
![image](https://user-images.githubusercontent.com/42398485/90332001-bb54ed80-df7e-11ea-9a6a-994475d8aa91.png)

**Comment by winterflame** [comment]
dupe
