### ISSUE TITLE
[TCO20-Southern Asia][Web-Edge] Post adding Fullname still getting validation messsage.

### ISSUE THREAD

**Issue by ab668685** [topcoder-platform/qa-fun#832]
Steps:-
1.Enter the URL - https://www.tutorialspoint.com/index.htm.
2. Click on add to cart any course
3. Redirects to Login page
4. Click on Create account
5. Click on Send OTP without adding Full Name & Email id
6. Gets a validation message
7. Now add Full Name without adding  Email id
8. Click on Send OTP

issue : Post adding Fullname, still getting validation message 

Expected Result : Should not get  validation message for Full Name ,should get for Email id
Device/Browser Name: Edge
OS Version : Windows 10

![image](https://user-images.githubusercontent.com/61318135/90332023-e79c5880-dfd6-11ea-87d7-6c30bea2a90c.png)

**Comment by winterflame** [comment]
dupe
