### ISSUE TITLE
[TCO20-Southern Asia][Web-Chrome] Categories list has unnecessary white/blank space

### ISSUE THREAD

**Issue by mmmengg-dev** [topcoder-platform/qa-fun#833]
Repro Steps:

1. Go to -> https://www.tutorialspoint.com/videotutorials/subscription.php
2. Click on 'Categories' drop down list
3. Notice after last list item i.e. Personal Development, there is lot of unnecessary white/blank space

Actual Result:
Categories list has unnecessary white/blank space

Expected Result:
List drop down should be limited to list items instead of hard coded length

Device/Browser Name:
Chrome-Version 84.0.4147.125 (Official Build) (64-bit)

OS Version:
Windows 8.1 64-bit Operating System

Screenshot/Screencast: 
![image](https://user-images.githubusercontent.com/68599579/90332089-9ccf1080-dfd7-11ea-8c03-e0f2541f4392.png)

**Comment by winterflame** [comment]
dupe
