### ISSUE TITLE
Open for Registration : sort by [A-Z] not functioning precisely

### ISSUE THREAD

**Issue by lavthaiba** [topcoder-platform/qa-fun#84]
**Steps to Reproduce:**
1. Login to topcoder.com and go to https://www.topcoder.com/challenges
2. On "Open for Registration" section select the sorting option as "[A-Z]"
3.  check weather the sorting for ascending order is working or not.

**Expected Result:**
It should sort the title by ascending order

**Actual Result:**
Title doesn't seem to sort by ascending order

**Screenshot as attached:**

![topcoderascerr](https://user-images.githubusercontent.com/10667786/75996824-8ac84c80-5f26-11ea-9569-82c8e10eec7f.PNG)

**Device/OS/Browser Information:**
Dell laptop Inspiron 3580/windows 10 pro 64-bit( 10.0 , build 18362)/chrome (version: 80.0.3987.132)

**Comment by winterflame** [comment]
Sorting is correct - the titles in the screenshot start with the character '['.
