### ISSUE TITLE
[TCO20-Southern Asia][Web-Firefox] course title long name is breaking the page Layout 

### ISSUE THREAD

**Issue by bhattashubham** [topcoder-platform/qa-fun#844]
**Repro Steps**
	
1 hhttps://www.tutorialspoint.com/videotutorials/user_course.php
2. in put values long name in course title and observe 

**Actual Result**
long name is breaking layout of page 

**Expected Result**
max character should be validate for the course title 

**Device/Browser Name**

Laptop /Firefox

**OS Version**

79.0 (64-bit)
**Screenshot/Screencast**
[bug42.zip](https://github.com/topcoder-platform/qa-fun/files/5080474/bug42.zip)

**Comment by winterflame** [comment]
dupe
