### ISSUE TITLE
Refresh the page after a text filter operation, the filter is not refreshed

### ISSUE THREAD

**Issue by fanwenlin** [topcoder-platform/qa-fun#85]
Bug Title:
Refresh the page after a text filter operation, the filter is not refreshed, but the date range filter is refreshed. At the same time, the "search challenge" field is refreshed.

Steps to Reproduce:
1. Go to https://www.topcoder.com/challenges
2. Enter some words(Such as "Flutter") and click search.
3. Go to https://www.topcoder.com/challenges again

Expected Result:
1. Searching field and filter are both cleared.
2. Searching field and filter are both kept.

Additional:
The text filter should have the same logic with the date range filter. But the date range filter was cleared while the text filter was kept.

Actual Result:
The searching field is cleared but the filtered answer is kept.

Device/OS/Browser Information:
Device: Dell Inspiron 7472
OS: Windows 10 Enterprise 19035.1000
Browser: Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by winterflame** [comment]
@fanwenlin Please provide a screencast or screenshots.

**Comment by fanwenlin** [comment]
Screencast:
![1](https://user-images.githubusercontent.com/17265932/76137626-4ea60080-607a-11ea-9887-fea0bc696cf9.png)
![2](https://user-images.githubusercontent.com/17265932/76137630-51a0f100-607a-11ea-8b31-d2e48a4c9ee9.png)
![3](https://user-images.githubusercontent.com/17265932/76137631-54034b00-607a-11ea-953d-233d2bc410a8.png)
