### ISSUE TITLE
[TCO20-North America][Web-Chrome]- Status dropdown is not clearing when user click on the Clear button

### ISSUE THREAD

**Issue by youdare** [topcoder-platform/qa-fun#853]
[TCO20-North America][Web-Chrome]- Based on location Default “English” language is not selected 
Reproduction Steps:
1.	Open the app https://www.w3schools.com/
2.	Click “Global” icon on the right top corner of the page
3.	Based on location Default “English” language is not selected 

 Actual Result: 
Based on location Default “English” language is not selected 

Expected Result: 
Based on location Default “English” language should be there 

Device/OS: Laptop | Windows 10 (64bit) | Chrome 85.0.4183.83| Edge 85.0.564.51| Firefox 79

![image](https://user-images.githubusercontent.com/31862600/93717107-76e1e200-fb28-11ea-8b85-50dd70a5122e.png)

**Comment by winterflame** [comment]
Looks like the title should be "[TCO20-North America][Web-Chrome]- Based on location Default “English” language is not selected".
