### ISSUE TITLE
filters don't change numbers of challenges in summary container on the right side

### ISSUE THREAD

**Issue by lucosmo** [topcoder-platform/qa-fun#86]
Bug Title: filters don't change numbers of challenges

Steps to Reproduce:

1. go to: https://www.topcoder.com/challenges
2. On the right side of screen there is small container containing: 'all challenges', 'my challenges', 'open for registration' etc
3. Above that container there are 3 filters (design, development, data science)
4. Turning on/off these filters doesn't change number of challenges in the container from step 2, but change what is in main challenges list.

Expected Result:
Applying 'design' filter should in summary show right number of challenges. 'All challenges' should be number only all 'design' challenges.

Actual Result:
Numbers in 'summary' container on the right don't change. 

Screenshots or screencast:
Summary container with all filters applied: 
![topcoder5](https://user-images.githubusercontent.com/3357786/76074665-9e5dcc80-5f93-11ea-9403-6045f1a4ffd0.png)

Summary container with only 'design' filter applied: 

![topcoder6](https://user-images.githubusercontent.com/3357786/76074660-9dc53600-5f93-11ea-8f03-3cb90f5e9e9d.png)

Device/OS/Browser Information:
Dell lntel Core i5/ Windows 10/ Google Chrome Version 80.0.3987.122 64bit

**Comment by winterflame** [comment]
This is as designed, not a bug.
