### ISSUE TITLE
Nav bar is Partially visible when Google Translate is on

### ISSUE THREAD

**Issue by chigirl** [topcoder-platform/qa-fun#864]
Issue:  Nav bar is partially shown when Google Translate is selected
Browser:  Safari

![image](https://user-images.githubusercontent.com/6310621/93717893-a0aa0180-fb46-11ea-875b-7de270824b7d.png)

Repo:  
1. Navigate to w3schools in Safari
2.  Click on Google Translate
3.  Observe Navbar. MORE is partially shown

Expected:
Nav bar elements to still be shown

Actual:
Nav bar elements partially shown

Tamikasue

**Comment by winterflame** [comment]
@chigirl Safari is not in scope. Please check challenge spec: https://www.topcoder.com/challenges/30142087/?type=develop

Chrome, Firefox and Edge are in scope.

**Comment by winterflame** [comment]
@chigirl Also, please remember to submit a zip file with your before submission phase ends.
