### ISSUE TITLE
[TCO20-North America][Web-Chrome] 'Select Language' appears in Translate drop down when we click any language after clicking English

### ISSUE THREAD

**Issue by hasinamahamootha** [topcoder-platform/qa-fun#871]
Repro Steps
1. Go to the website https://www.w3schools.com/
2. Click Translate w3schools icon.
3. Click the Dropdown
4. Select the language 'Sindhi'
5. Click the dropdown again and select the language 'English'.
6. click the dropdown again and select the language 'Sindhi' again.

Expected Result
'Sindhi' language should be selected and the page should be translated to Sindhi.

Actual Result
'Select language' appears in the dropdown and the page is not translated to sindhi.

Device/Browser Name
Laptop | Windows 10 (64bit) | Chrome 85.0.4183.102 

OS Version
Windows 10 version 1903

Screenshot/Screencast:
Please find the link below for the bug:
https://wipro365-my.sharepoint.com/:v:/g/personal/ha20018067_wipro_com/ESYNpFiHye1Pvq_jp5zz7z4BmAv2psH63N_KMDrWbj9uhw?e=uwhIvf

**Comment by winterflame** [comment]
@hasinamahamootha Please attach the screenshot in the comment - I'm unable to access the link above.

**Comment by hasinamahamootha** [comment]
Please ignore the above link for the video. please find the new link here,:
https://drive.google.com/file/d/1sd7sNXfNUoo-9sW8kaPI4J_S1PDEB9_r/view?usp=sharing

**Comment by winterflame** [comment]
Hi @hasinamahamootha , actually you can drag and drop the image in the comment area.

**Comment by winterflame** [comment]
OK.
