### ISSUE TITLE
[TCO20-Eastern Asia][Web-Edge] Both Yes and No are checked if you check either Yes or No in the Advertisement Feedback form.

### ISSUE THREAD

**Issue by shindannin** [topcoder-platform/qa-fun#882]
shindannin (=NobuMiu's github account)

**Repro Steps:**
1. Open https://www.wayfair.com/pet/cat/pet-c504273.html on Edge
2. Go to the link Advertisement Feedback
3. Click Yes (or No)

**Actual Result:**
Both Yes and No are checked, so we cannot get a meaningful feedback from customers.

**Expected Result:**
Only Yes should be checked.

**OS Name/Version:**
Windows 10 (Version 2004, OS Build 19041.508)

![image](https://user-images.githubusercontent.com/8682966/94330619-aa28e300-fff8-11ea-8855-b4d7ea881050.png)

**Comment by winterflame** [comment]
@shindannin Please submit if you haven't yet.
