### ISSUE TITLE
[TCO20-Eastern Asia][Web-Edge] The page asks sign-in even if the customer has already signed-in by his google account.

### ISSUE THREAD

**Issue by shindannin** [topcoder-platform/qa-fun#887]
shindannin (=NobuMiu's github account)

Repro Steps:
- Create an account by using a google account.
- Go to http://wayfair.com/plan
- Click cart on the right.
You can see the account name on the top but they asks sign-in to see inside of my cart.

Actual Result:
The page asks the customer to sign-in.

Expected Result:
The customer does not need to sign-in again.

OS Name/Version:
Windows 10 (Version 2004, OS Build 19041.508)

![image](https://user-images.githubusercontent.com/8682966/94335393-f599bc00-000d-11eb-809c-7147e019fd46.png)

**Comment by winterflame** [comment]
@shindannin Please remember to submit a text file, less than 15 minutes left! You can submit it right now.

**Comment by shindannin** [comment]
Yes I did it. :)

**Comment by winterflame** [comment]
Cool, saw that.
