### ISSUE TITLE
[Firefox] Bottom link not consistent content link on sidebar and footer

### ISSUE THREAD

**Issue by degraphic** [topcoder-platform/qa-fun#91]
#### Expected behavior
Bottom link (About • Contact • Help • Privacy • Terms) 
should consistent content link on sidebar and footer

#### Actual behavior
Bottom link (About • Contact • Help • Privacy • Terms) 
not consistent content link on sidebar and footer

#### Steps to reproduce the problem

 1. Open the Browser then type https://www.topcoder.com/challenges
 2. Then we can check bottom link on right side bar  and  bottom link footer with inspect element
3. Then we can check and compared the content, by clicking one of bottom link, 
for example we click 'about' link on side bar and click 'About Us' on Footer

#### Screenshot/screencast
![Screen Shot 2020-03-07 at 16 43 32](https://user-images.githubusercontent.com/4364214/76141215-abaeb000-6094-11ea-9e3d-d6fcef9b268a.png)
![Screen Shot 2020-03-07 at 16 42 27](https://user-images.githubusercontent.com/4364214/76141217-b0736400-6094-11ea-89f7-6eda7bac6585.png)

#### Environment

    OS: MacOs Mojave 10.14.6
    Browser (w/version): Mozilla Firefox Version 73.0.1  (64-bit)

**Comment by winterflame** [comment]
Seems the contents on the right side should be removed.
