### ISSUE TITLE
[Firefox] Challenge deadlines does not update

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#95]
Bug Title: In case challenge deadlines are changed, reloading the challenge page doesn't update the deadlines. Hard-reload updates the deadlines.
Steps to Reproduce:
1. Open a challenge page
2. Challenge admin modifies challenge deadlines
3. Reload the challenge page any number of times, it shows un-updated deadlines.

Expected Result:
Deadlines should be updated as done by challenge admin

Actual Result:
Old deadlines are shown.

Device/OS/Browser Information:
Ubuntu 18.04 LTS, Firefox 73.0.1 (64-bit)

**Comment by g1tman** [comment]
Tested on both ubuntu & windows

**Comment by winterflame** [comment]
1) Missing screenshots or screencast.
2) The challenge data is fetched from cache, need to add "nocache=true" to get latest data.
