### ISSUE TITLE
[Firefox] All Challenges option disabled when filter applied

### ISSUE THREAD

**Issue by g1tman** [topcoder-platform/qa-fun#97]
Bug Title: 'All Challenges' button is disabled when filters are applied.

Steps to Reproduce:
1. Apply a filter on all challenges

Expected Result:
After applying filter, 'All challenges' button should be enabled

Actual Result:
'All Challenges' button remains disabled

Device/OS/Browser Information:
Ubuntu 18.04 LTS, Firefox 73.0.1 (64-bit)

**Comment by g1tman** [comment]
Tested on both ubuntu & windows

**Comment by winterflame** [comment]
@g1tman Please attach a screenshot, thanks.
